// Code generated by protoc-gen-go. DO NOT EDIT.
// source: breez.proto

/*
Package breez is a generated protocol buffer package.

It is generated from these files:
	breez.proto

It has these top-level messages:
	OpenChannelRequest
	OpenChannelReply
	AddFundRequest
	AddFundReply
	AddFundStatusRequest
	AddFundStatusReply
	RemoveFundRequest
	RemoveFundReply
	GetPaymentRequest
	GetPaymentReply
	GetFundLimitsRequest
	GetFundLimitsReply
	MempoolRegisterRequest
	MempoolRegisterReply
	PingRequest
	PingReply
*/
package breez

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OpenChannelRequest struct {
	PubKey string `protobuf:"bytes,1,opt,name=pubKey" json:"pubKey,omitempty"`
}

func (m *OpenChannelRequest) Reset()                    { *m = OpenChannelRequest{} }
func (m *OpenChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*OpenChannelRequest) ProtoMessage()               {}
func (*OpenChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OpenChannelRequest) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

type OpenChannelReply struct {
}

func (m *OpenChannelReply) Reset()                    { *m = OpenChannelReply{} }
func (m *OpenChannelReply) String() string            { return proto.CompactTextString(m) }
func (*OpenChannelReply) ProtoMessage()               {}
func (*OpenChannelReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type AddFundRequest struct {
	PaymentRequest    string `protobuf:"bytes,1,opt,name=paymentRequest" json:"paymentRequest,omitempty"`
	NotificationToken string `protobuf:"bytes,2,opt,name=notificationToken" json:"notificationToken,omitempty"`
}

func (m *AddFundRequest) Reset()                    { *m = AddFundRequest{} }
func (m *AddFundRequest) String() string            { return proto.CompactTextString(m) }
func (*AddFundRequest) ProtoMessage()               {}
func (*AddFundRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddFundRequest) GetPaymentRequest() string {
	if m != nil {
		return m.PaymentRequest
	}
	return ""
}

func (m *AddFundRequest) GetNotificationToken() string {
	if m != nil {
		return m.NotificationToken
	}
	return ""
}

type AddFundReply struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *AddFundReply) Reset()                    { *m = AddFundReply{} }
func (m *AddFundReply) String() string            { return proto.CompactTextString(m) }
func (*AddFundReply) ProtoMessage()               {}
func (*AddFundReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddFundReply) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type AddFundStatusRequest struct {
	Addresses         []string `protobuf:"bytes,1,rep,name=addresses" json:"addresses,omitempty"`
	NotificationToken string   `protobuf:"bytes,2,opt,name=notificationToken" json:"notificationToken,omitempty"`
}

func (m *AddFundStatusRequest) Reset()                    { *m = AddFundStatusRequest{} }
func (m *AddFundStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*AddFundStatusRequest) ProtoMessage()               {}
func (*AddFundStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AddFundStatusRequest) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *AddFundStatusRequest) GetNotificationToken() string {
	if m != nil {
		return m.NotificationToken
	}
	return ""
}

type AddFundStatusReply struct {
	Statuses map[string]*AddFundStatusReply_AddressStatus `protobuf:"bytes,1,rep,name=statuses" json:"statuses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AddFundStatusReply) Reset()                    { *m = AddFundStatusReply{} }
func (m *AddFundStatusReply) String() string            { return proto.CompactTextString(m) }
func (*AddFundStatusReply) ProtoMessage()               {}
func (*AddFundStatusReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AddFundStatusReply) GetStatuses() map[string]*AddFundStatusReply_AddressStatus {
	if m != nil {
		return m.Statuses
	}
	return nil
}

type AddFundStatusReply_AddressStatus struct {
	Tx        string `protobuf:"bytes,1,opt,name=tx" json:"tx,omitempty"`
	Amount    int64  `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
	Confirmed bool   `protobuf:"varint,3,opt,name=confirmed" json:"confirmed,omitempty"`
	BlockHash string `protobuf:"bytes,4,opt,name=blockHash" json:"blockHash,omitempty"`
}

func (m *AddFundStatusReply_AddressStatus) Reset()         { *m = AddFundStatusReply_AddressStatus{} }
func (m *AddFundStatusReply_AddressStatus) String() string { return proto.CompactTextString(m) }
func (*AddFundStatusReply_AddressStatus) ProtoMessage()    {}
func (*AddFundStatusReply_AddressStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5, 0}
}

func (m *AddFundStatusReply_AddressStatus) GetTx() string {
	if m != nil {
		return m.Tx
	}
	return ""
}

func (m *AddFundStatusReply_AddressStatus) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *AddFundStatusReply_AddressStatus) GetConfirmed() bool {
	if m != nil {
		return m.Confirmed
	}
	return false
}

func (m *AddFundStatusReply_AddressStatus) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

type RemoveFundRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Amount  int64  `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *RemoveFundRequest) Reset()                    { *m = RemoveFundRequest{} }
func (m *RemoveFundRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveFundRequest) ProtoMessage()               {}
func (*RemoveFundRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RemoveFundRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RemoveFundRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type RemoveFundReply struct {
}

func (m *RemoveFundReply) Reset()                    { *m = RemoveFundReply{} }
func (m *RemoveFundReply) String() string            { return proto.CompactTextString(m) }
func (*RemoveFundReply) ProtoMessage()               {}
func (*RemoveFundReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type GetPaymentRequest struct {
	PaymentRequest string `protobuf:"bytes,1,opt,name=paymentRequest" json:"paymentRequest,omitempty"`
	Address        string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *GetPaymentRequest) Reset()                    { *m = GetPaymentRequest{} }
func (m *GetPaymentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPaymentRequest) ProtoMessage()               {}
func (*GetPaymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetPaymentRequest) GetPaymentRequest() string {
	if m != nil {
		return m.PaymentRequest
	}
	return ""
}

func (m *GetPaymentRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type GetPaymentReply struct {
	PaymentError string `protobuf:"bytes,1,opt,name=paymentError" json:"paymentError,omitempty"`
}

func (m *GetPaymentReply) Reset()                    { *m = GetPaymentReply{} }
func (m *GetPaymentReply) String() string            { return proto.CompactTextString(m) }
func (*GetPaymentReply) ProtoMessage()               {}
func (*GetPaymentReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetPaymentReply) GetPaymentError() string {
	if m != nil {
		return m.PaymentError
	}
	return ""
}

type GetFundLimitsRequest struct {
	LightningID string `protobuf:"bytes,1,opt,name=lightningID" json:"lightningID,omitempty"`
}

func (m *GetFundLimitsRequest) Reset()                    { *m = GetFundLimitsRequest{} }
func (m *GetFundLimitsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetFundLimitsRequest) ProtoMessage()               {}
func (*GetFundLimitsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetFundLimitsRequest) GetLightningID() string {
	if m != nil {
		return m.LightningID
	}
	return ""
}

type GetFundLimitsReply struct {
	MaxDepositAmount        int64 `protobuf:"varint,1,opt,name=maxDepositAmount" json:"maxDepositAmount,omitempty"`
	DepositBalanceThreshold int64 `protobuf:"varint,2,opt,name=depositBalanceThreshold" json:"depositBalanceThreshold,omitempty"`
}

func (m *GetFundLimitsReply) Reset()                    { *m = GetFundLimitsReply{} }
func (m *GetFundLimitsReply) String() string            { return proto.CompactTextString(m) }
func (*GetFundLimitsReply) ProtoMessage()               {}
func (*GetFundLimitsReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetFundLimitsReply) GetMaxDepositAmount() int64 {
	if m != nil {
		return m.MaxDepositAmount
	}
	return 0
}

func (m *GetFundLimitsReply) GetDepositBalanceThreshold() int64 {
	if m != nil {
		return m.DepositBalanceThreshold
	}
	return 0
}

type MempoolRegisterRequest struct {
	ClientID  string   `protobuf:"bytes,1,opt,name=clientID" json:"clientID,omitempty"`
	Addresses []string `protobuf:"bytes,2,rep,name=addresses" json:"addresses,omitempty"`
}

func (m *MempoolRegisterRequest) Reset()                    { *m = MempoolRegisterRequest{} }
func (m *MempoolRegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*MempoolRegisterRequest) ProtoMessage()               {}
func (*MempoolRegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *MempoolRegisterRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *MempoolRegisterRequest) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type MempoolRegisterReply struct {
	TXS []*MempoolRegisterReply_Transaction `protobuf:"bytes,1,rep,name=TXS" json:"TXS,omitempty"`
}

func (m *MempoolRegisterReply) Reset()                    { *m = MempoolRegisterReply{} }
func (m *MempoolRegisterReply) String() string            { return proto.CompactTextString(m) }
func (*MempoolRegisterReply) ProtoMessage()               {}
func (*MempoolRegisterReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *MempoolRegisterReply) GetTXS() []*MempoolRegisterReply_Transaction {
	if m != nil {
		return m.TXS
	}
	return nil
}

type MempoolRegisterReply_Transaction struct {
	TX      string  `protobuf:"bytes,1,opt,name=TX" json:"TX,omitempty"`
	Address string  `protobuf:"bytes,2,opt,name=Address" json:"Address,omitempty"`
	Value   float64 `protobuf:"fixed64,3,opt,name=Value" json:"Value,omitempty"`
}

func (m *MempoolRegisterReply_Transaction) Reset()         { *m = MempoolRegisterReply_Transaction{} }
func (m *MempoolRegisterReply_Transaction) String() string { return proto.CompactTextString(m) }
func (*MempoolRegisterReply_Transaction) ProtoMessage()    {}
func (*MempoolRegisterReply_Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{13, 0}
}

func (m *MempoolRegisterReply_Transaction) GetTX() string {
	if m != nil {
		return m.TX
	}
	return ""
}

func (m *MempoolRegisterReply_Transaction) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *MempoolRegisterReply_Transaction) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type PingRequest struct {
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type PingReply struct {
	Version string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
}

func (m *PingReply) Reset()                    { *m = PingReply{} }
func (m *PingReply) String() string            { return proto.CompactTextString(m) }
func (*PingReply) ProtoMessage()               {}
func (*PingReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *PingReply) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*OpenChannelRequest)(nil), "breez.OpenChannelRequest")
	proto.RegisterType((*OpenChannelReply)(nil), "breez.OpenChannelReply")
	proto.RegisterType((*AddFundRequest)(nil), "breez.AddFundRequest")
	proto.RegisterType((*AddFundReply)(nil), "breez.AddFundReply")
	proto.RegisterType((*AddFundStatusRequest)(nil), "breez.AddFundStatusRequest")
	proto.RegisterType((*AddFundStatusReply)(nil), "breez.AddFundStatusReply")
	proto.RegisterType((*AddFundStatusReply_AddressStatus)(nil), "breez.AddFundStatusReply.AddressStatus")
	proto.RegisterType((*RemoveFundRequest)(nil), "breez.RemoveFundRequest")
	proto.RegisterType((*RemoveFundReply)(nil), "breez.RemoveFundReply")
	proto.RegisterType((*GetPaymentRequest)(nil), "breez.GetPaymentRequest")
	proto.RegisterType((*GetPaymentReply)(nil), "breez.GetPaymentReply")
	proto.RegisterType((*GetFundLimitsRequest)(nil), "breez.GetFundLimitsRequest")
	proto.RegisterType((*GetFundLimitsReply)(nil), "breez.GetFundLimitsReply")
	proto.RegisterType((*MempoolRegisterRequest)(nil), "breez.MempoolRegisterRequest")
	proto.RegisterType((*MempoolRegisterReply)(nil), "breez.MempoolRegisterReply")
	proto.RegisterType((*MempoolRegisterReply_Transaction)(nil), "breez.MempoolRegisterReply.Transaction")
	proto.RegisterType((*PingRequest)(nil), "breez.PingRequest")
	proto.RegisterType((*PingReply)(nil), "breez.PingReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Information service

type InformationClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
}

type informationClient struct {
	cc *grpc.ClientConn
}

func NewInformationClient(cc *grpc.ClientConn) InformationClient {
	return &informationClient{cc}
}

func (c *informationClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := grpc.Invoke(ctx, "/breez.Information/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Information service

type InformationServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
}

func RegisterInformationServer(s *grpc.Server, srv InformationServer) {
	s.RegisterService(&_Information_serviceDesc, srv)
}

func _Information_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InformationServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breez.Information/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InformationServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Information_serviceDesc = grpc.ServiceDesc{
	ServiceName: "breez.Information",
	HandlerType: (*InformationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Information_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "breez.proto",
}

// Client API for MempoolNotifier service

type MempoolNotifierClient interface {
	MempoolRegister(ctx context.Context, in *MempoolRegisterRequest, opts ...grpc.CallOption) (*MempoolRegisterReply, error)
}

type mempoolNotifierClient struct {
	cc *grpc.ClientConn
}

func NewMempoolNotifierClient(cc *grpc.ClientConn) MempoolNotifierClient {
	return &mempoolNotifierClient{cc}
}

func (c *mempoolNotifierClient) MempoolRegister(ctx context.Context, in *MempoolRegisterRequest, opts ...grpc.CallOption) (*MempoolRegisterReply, error) {
	out := new(MempoolRegisterReply)
	err := grpc.Invoke(ctx, "/breez.MempoolNotifier/MempoolRegister", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MempoolNotifier service

type MempoolNotifierServer interface {
	MempoolRegister(context.Context, *MempoolRegisterRequest) (*MempoolRegisterReply, error)
}

func RegisterMempoolNotifierServer(s *grpc.Server, srv MempoolNotifierServer) {
	s.RegisterService(&_MempoolNotifier_serviceDesc, srv)
}

func _MempoolNotifier_MempoolRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MempoolRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MempoolNotifierServer).MempoolRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breez.MempoolNotifier/MempoolRegister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MempoolNotifierServer).MempoolRegister(ctx, req.(*MempoolRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MempoolNotifier_serviceDesc = grpc.ServiceDesc{
	ServiceName: "breez.MempoolNotifier",
	HandlerType: (*MempoolNotifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MempoolRegister",
			Handler:    _MempoolNotifier_MempoolRegister_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "breez.proto",
}

// Client API for FundManager service

type FundManagerClient interface {
	OpenChannel(ctx context.Context, in *OpenChannelRequest, opts ...grpc.CallOption) (*OpenChannelReply, error)
	AddFund(ctx context.Context, in *AddFundRequest, opts ...grpc.CallOption) (*AddFundReply, error)
	AddFundStatus(ctx context.Context, in *AddFundStatusRequest, opts ...grpc.CallOption) (*AddFundStatusReply, error)
	RemoveFund(ctx context.Context, in *RemoveFundRequest, opts ...grpc.CallOption) (*RemoveFundReply, error)
	GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...grpc.CallOption) (*GetPaymentReply, error)
	GetFundLimits(ctx context.Context, in *GetFundLimitsRequest, opts ...grpc.CallOption) (*GetFundLimitsReply, error)
}

type fundManagerClient struct {
	cc *grpc.ClientConn
}

func NewFundManagerClient(cc *grpc.ClientConn) FundManagerClient {
	return &fundManagerClient{cc}
}

func (c *fundManagerClient) OpenChannel(ctx context.Context, in *OpenChannelRequest, opts ...grpc.CallOption) (*OpenChannelReply, error) {
	out := new(OpenChannelReply)
	err := grpc.Invoke(ctx, "/breez.FundManager/OpenChannel", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundManagerClient) AddFund(ctx context.Context, in *AddFundRequest, opts ...grpc.CallOption) (*AddFundReply, error) {
	out := new(AddFundReply)
	err := grpc.Invoke(ctx, "/breez.FundManager/AddFund", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundManagerClient) AddFundStatus(ctx context.Context, in *AddFundStatusRequest, opts ...grpc.CallOption) (*AddFundStatusReply, error) {
	out := new(AddFundStatusReply)
	err := grpc.Invoke(ctx, "/breez.FundManager/AddFundStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundManagerClient) RemoveFund(ctx context.Context, in *RemoveFundRequest, opts ...grpc.CallOption) (*RemoveFundReply, error) {
	out := new(RemoveFundReply)
	err := grpc.Invoke(ctx, "/breez.FundManager/RemoveFund", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundManagerClient) GetPayment(ctx context.Context, in *GetPaymentRequest, opts ...grpc.CallOption) (*GetPaymentReply, error) {
	out := new(GetPaymentReply)
	err := grpc.Invoke(ctx, "/breez.FundManager/GetPayment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundManagerClient) GetFundLimits(ctx context.Context, in *GetFundLimitsRequest, opts ...grpc.CallOption) (*GetFundLimitsReply, error) {
	out := new(GetFundLimitsReply)
	err := grpc.Invoke(ctx, "/breez.FundManager/GetFundLimits", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FundManager service

type FundManagerServer interface {
	OpenChannel(context.Context, *OpenChannelRequest) (*OpenChannelReply, error)
	AddFund(context.Context, *AddFundRequest) (*AddFundReply, error)
	AddFundStatus(context.Context, *AddFundStatusRequest) (*AddFundStatusReply, error)
	RemoveFund(context.Context, *RemoveFundRequest) (*RemoveFundReply, error)
	GetPayment(context.Context, *GetPaymentRequest) (*GetPaymentReply, error)
	GetFundLimits(context.Context, *GetFundLimitsRequest) (*GetFundLimitsReply, error)
}

func RegisterFundManagerServer(s *grpc.Server, srv FundManagerServer) {
	s.RegisterService(&_FundManager_serviceDesc, srv)
}

func _FundManager_OpenChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundManagerServer).OpenChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breez.FundManager/OpenChannel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundManagerServer).OpenChannel(ctx, req.(*OpenChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundManager_AddFund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundManagerServer).AddFund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breez.FundManager/AddFund",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundManagerServer).AddFund(ctx, req.(*AddFundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundManager_AddFundStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFundStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundManagerServer).AddFundStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breez.FundManager/AddFundStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundManagerServer).AddFundStatus(ctx, req.(*AddFundStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundManager_RemoveFund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundManagerServer).RemoveFund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breez.FundManager/RemoveFund",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundManagerServer).RemoveFund(ctx, req.(*RemoveFundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundManager_GetPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundManagerServer).GetPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breez.FundManager/GetPayment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundManagerServer).GetPayment(ctx, req.(*GetPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundManager_GetFundLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFundLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundManagerServer).GetFundLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/breez.FundManager/GetFundLimits",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundManagerServer).GetFundLimits(ctx, req.(*GetFundLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FundManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "breez.FundManager",
	HandlerType: (*FundManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenChannel",
			Handler:    _FundManager_OpenChannel_Handler,
		},
		{
			MethodName: "AddFund",
			Handler:    _FundManager_AddFund_Handler,
		},
		{
			MethodName: "AddFundStatus",
			Handler:    _FundManager_AddFundStatus_Handler,
		},
		{
			MethodName: "RemoveFund",
			Handler:    _FundManager_RemoveFund_Handler,
		},
		{
			MethodName: "GetPayment",
			Handler:    _FundManager_GetPayment_Handler,
		},
		{
			MethodName: "GetFundLimits",
			Handler:    _FundManager_GetFundLimits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "breez.proto",
}

func init() { proto.RegisterFile("breez.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 787 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x5f, 0x4f, 0xdb, 0x48,
	0x10, 0x8f, 0x13, 0xe0, 0xc8, 0x98, 0x3f, 0xc9, 0x5e, 0x80, 0x10, 0xee, 0x24, 0xb4, 0x12, 0x77,
	0xd1, 0x09, 0xe5, 0x21, 0xa7, 0xd3, 0xd1, 0x4a, 0x48, 0x4d, 0x80, 0x52, 0xd4, 0x52, 0x22, 0x93,
	0x56, 0xbc, 0x3a, 0xf6, 0x26, 0xb1, 0xb0, 0x77, 0xdd, 0xf5, 0x26, 0x22, 0x7c, 0x9a, 0xbe, 0xf4,
	0x1b, 0xf4, 0x03, 0x56, 0x6b, 0xaf, 0x1d, 0x3b, 0x4e, 0x50, 0xfb, 0xe6, 0xf9, 0xed, 0xcc, 0x6f,
	0x67, 0x66, 0x67, 0x7e, 0x06, 0x7d, 0xc0, 0x09, 0x79, 0x6e, 0xf9, 0x9c, 0x09, 0x86, 0xd6, 0x43,
	0x03, 0x9f, 0x02, 0xba, 0xf3, 0x09, 0xbd, 0x18, 0x9b, 0x94, 0x12, 0xd7, 0x20, 0x5f, 0x26, 0x24,
	0x10, 0x68, 0x1f, 0x36, 0xfc, 0xc9, 0xe0, 0x3d, 0x99, 0xd5, 0xb5, 0x63, 0xad, 0x59, 0x36, 0x94,
	0x85, 0x11, 0x54, 0x32, 0xde, 0xbe, 0x3b, 0xc3, 0x43, 0xd8, 0xe9, 0xd8, 0xf6, 0xdb, 0x09, 0xb5,
	0xe3, 0xe8, 0xbf, 0x60, 0xc7, 0x37, 0x67, 0x1e, 0xa1, 0x42, 0x21, 0x8a, 0x65, 0x01, 0x45, 0xa7,
	0x50, 0xa5, 0x4c, 0x38, 0x43, 0xc7, 0x32, 0x85, 0xc3, 0x68, 0x9f, 0x3d, 0x12, 0x5a, 0x2f, 0x86,
	0xae, 0xf9, 0x03, 0xdc, 0x84, 0xad, 0xe4, 0x1e, 0xdf, 0x9d, 0xa1, 0x3a, 0xfc, 0x66, 0xda, 0x36,
	0x27, 0x41, 0xa0, 0xe8, 0x63, 0x13, 0x0f, 0xa0, 0xa6, 0x3c, 0xef, 0x85, 0x29, 0x26, 0x41, 0x7c,
	0xdf, 0x1f, 0x50, 0x56, 0x2e, 0x44, 0xc6, 0x94, 0x9a, 0x65, 0x63, 0x0e, 0xfc, 0x62, 0x36, 0xdf,
	0x8b, 0x80, 0x16, 0x2e, 0x91, 0x49, 0x5d, 0xc0, 0x66, 0x10, 0x9a, 0xea, 0x06, 0xbd, 0xfd, 0x77,
	0x2b, 0xea, 0x7a, 0xde, 0xb9, 0x75, 0xaf, 0x3c, 0xaf, 0xa8, 0xe0, 0x33, 0x23, 0x09, 0x6c, 0x04,
	0xb0, 0xdd, 0x89, 0xd2, 0x8a, 0x3c, 0xd0, 0x0e, 0x14, 0xc5, 0x93, 0xaa, 0xb2, 0x28, 0x9e, 0xe4,
	0xf3, 0x98, 0x1e, 0x9b, 0x50, 0x11, 0xe6, 0x57, 0x32, 0x94, 0x25, 0x0b, 0xb4, 0x18, 0x1d, 0x3a,
	0xdc, 0x23, 0x76, 0xbd, 0x74, 0xac, 0x35, 0x37, 0x8d, 0x39, 0x20, 0x4f, 0x07, 0x2e, 0xb3, 0x1e,
	0xdf, 0x99, 0xc1, 0xb8, 0xbe, 0x16, 0x92, 0xcd, 0x81, 0x86, 0x0d, 0xdb, 0x99, 0x7c, 0x50, 0x05,
	0x4a, 0x8f, 0xc9, 0x00, 0xc8, 0x4f, 0x74, 0x0e, 0xeb, 0x53, 0xd3, 0x9d, 0x90, 0xf0, 0xd6, 0x17,
	0x2b, 0xcb, 0xa4, 0x6f, 0x44, 0x51, 0xaf, 0x8b, 0x67, 0x1a, 0xbe, 0x82, 0xaa, 0x41, 0x3c, 0x36,
	0x25, 0xe9, 0x79, 0x59, 0xf9, 0x92, 0xab, 0x0a, 0xc5, 0x55, 0xd8, 0x4d, 0xd3, 0xc8, 0x31, 0xfc,
	0x04, 0xd5, 0x6b, 0x22, 0x7a, 0xd9, 0x09, 0xfb, 0xd9, 0x49, 0x4c, 0x65, 0x50, 0xcc, 0xce, 0xd2,
	0x7f, 0xb0, 0x9b, 0xa6, 0x95, 0x6f, 0x8c, 0x61, 0x4b, 0x85, 0x5f, 0x71, 0xce, 0xb8, 0xa2, 0xcc,
	0x60, 0xf8, 0x0c, 0x6a, 0xd7, 0x44, 0xc8, 0xec, 0x3e, 0x38, 0x9e, 0x23, 0x92, 0x11, 0x3c, 0x06,
	0xdd, 0x75, 0x46, 0x63, 0x41, 0x1d, 0x3a, 0xba, 0xb9, 0x54, 0xa1, 0x69, 0x08, 0x3f, 0x03, 0x5a,
	0x88, 0x94, 0x77, 0xfe, 0x03, 0x15, 0xcf, 0x7c, 0xba, 0x24, 0x3e, 0x0b, 0x1c, 0xd1, 0x89, 0x5a,
	0xa2, 0x85, 0x2d, 0xc9, 0xe1, 0xe8, 0x0c, 0x0e, 0xec, 0x08, 0xe8, 0x9a, 0xae, 0x49, 0x2d, 0xd2,
	0x1f, 0x73, 0x12, 0x8c, 0x99, 0x6b, 0xab, 0x2e, 0xae, 0x3a, 0xc6, 0x06, 0xec, 0xdf, 0x12, 0xcf,
	0x67, 0xcc, 0x35, 0xc8, 0xc8, 0x09, 0x04, 0xe1, 0x71, 0xde, 0x0d, 0xd8, 0xb4, 0x5c, 0x87, 0x50,
	0x91, 0x24, 0x9d, 0xd8, 0xd9, 0xb5, 0x2a, 0x2e, 0xac, 0x15, 0xfe, 0xaa, 0x41, 0x2d, 0x47, 0x2a,
	0x4b, 0x7a, 0x05, 0xa5, 0xfe, 0xc3, 0xfd, 0xc2, 0x96, 0x2c, 0xf3, 0x6c, 0xf5, 0xb9, 0x49, 0x03,
	0xd3, 0x92, 0xcb, 0x67, 0xc8, 0x98, 0xc6, 0x2d, 0xe8, 0x29, 0x4c, 0xae, 0x47, 0xff, 0x21, 0x5e,
	0x8f, 0xfe, 0x83, 0x7c, 0xcd, 0x4e, 0xf6, 0x35, 0x95, 0x89, 0x6a, 0xb0, 0xfe, 0x39, 0x9c, 0x60,
	0xb9, 0x1c, 0x9a, 0x11, 0x19, 0x78, 0x1b, 0xf4, 0x9e, 0x43, 0x47, 0xaa, 0x56, 0x7c, 0x02, 0xe5,
	0xc8, 0x54, 0x2a, 0x33, 0x25, 0x3c, 0x70, 0x18, 0x8d, 0x67, 0x53, 0x99, 0xed, 0x73, 0xd0, 0x6f,
	0xe8, 0x90, 0x71, 0x2f, 0x54, 0x05, 0xd4, 0x82, 0x35, 0x19, 0x85, 0x90, 0xaa, 0x24, 0xc5, 0xd8,
	0xa8, 0x64, 0x30, 0x39, 0xad, 0x85, 0xf6, 0x00, 0x76, 0x55, 0xb1, 0x1f, 0x43, 0x71, 0x21, 0x1c,
	0xdd, 0x25, 0x50, 0x5c, 0x3f, 0xfa, 0x73, 0x55, 0x5f, 0x22, 0xe2, 0xa3, 0x17, 0xda, 0x86, 0x0b,
	0xed, 0x6f, 0x25, 0xd0, 0xe5, 0x24, 0xdd, 0x9a, 0xd4, 0x1c, 0x11, 0x8e, 0x2e, 0x40, 0x4f, 0xc9,
	0x37, 0x3a, 0x54, 0xd1, 0xf9, 0x1f, 0x40, 0xe3, 0x60, 0xd9, 0x51, 0x48, 0x8a, 0xfe, 0x0f, 0xbb,
	0x2b, 0x69, 0xd1, 0x5e, 0x56, 0x01, 0xe2, 0xe0, 0xdf, 0x17, 0xe1, 0x28, 0xf0, 0x26, 0x94, 0xb5,
	0xb9, 0x54, 0xa0, 0xa3, 0xe5, 0x02, 0x12, 0x91, 0x1c, 0xae, 0x54, 0x17, 0x5c, 0x40, 0x6f, 0x00,
	0xe6, 0xfb, 0x8f, 0xea, 0xca, 0x35, 0xa7, 0x2c, 0x8d, 0xfd, 0x25, 0x27, 0x09, 0xc3, 0x7c, 0xaf,
	0x13, 0x86, 0x9c, 0x82, 0x24, 0x0c, 0x0b, 0x22, 0x10, 0x95, 0x93, 0x59, 0xd4, 0xa4, 0x9c, 0x65,
	0x8b, 0x9f, 0x94, 0x93, 0xdf, 0x6d, 0x5c, 0xe8, 0x9e, 0xc0, 0x9e, 0xc3, 0x5a, 0x23, 0xee, 0x5b,
	0xca, 0x2b, 0x20, 0x7c, 0xea, 0x58, 0xa4, 0x0b, 0x5d, 0x69, 0xf6, 0xe4, 0x0f, 0xbb, 0xa7, 0x0d,
	0x36, 0xc2, 0x3f, 0xf7, 0xbf, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x31, 0x5e, 0x0f, 0xc8,
	0x07, 0x00, 0x00,
}
