// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package data

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Account_AccountStatus int32

const (
	Account_WAITING_DEPOSIT              Account_AccountStatus = 0
	Account_WAITING_DEPOSIT_CONFIRMATION Account_AccountStatus = 1
	Account_PROCESSING_BREEZ_CONNECTION  Account_AccountStatus = 2
	Account_PROCESSING_WITHDRAWAL        Account_AccountStatus = 3
	Account_ACTIVE                       Account_AccountStatus = 4
)

var Account_AccountStatus_name = map[int32]string{
	0: "WAITING_DEPOSIT",
	1: "WAITING_DEPOSIT_CONFIRMATION",
	2: "PROCESSING_BREEZ_CONNECTION",
	3: "PROCESSING_WITHDRAWAL",
	4: "ACTIVE",
}
var Account_AccountStatus_value = map[string]int32{
	"WAITING_DEPOSIT":              0,
	"WAITING_DEPOSIT_CONFIRMATION": 1,
	"PROCESSING_BREEZ_CONNECTION":  2,
	"PROCESSING_WITHDRAWAL":        3,
	"ACTIVE":                       4,
}

func (x Account_AccountStatus) String() string {
	return proto.EnumName(Account_AccountStatus_name, int32(x))
}
func (Account_AccountStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{1, 0}
}

type Payment_PaymentType int32

const (
	Payment_DEPOSIT    Payment_PaymentType = 0
	Payment_WITHDRAWAL Payment_PaymentType = 1
	Payment_SENT       Payment_PaymentType = 2
	Payment_RECEIVED   Payment_PaymentType = 3
)

var Payment_PaymentType_name = map[int32]string{
	0: "DEPOSIT",
	1: "WITHDRAWAL",
	2: "SENT",
	3: "RECEIVED",
}
var Payment_PaymentType_value = map[string]int32{
	"DEPOSIT":    0,
	"WITHDRAWAL": 1,
	"SENT":       2,
	"RECEIVED":   3,
}

func (x Payment_PaymentType) String() string {
	return proto.EnumName(Payment_PaymentType_name, int32(x))
}
func (Payment_PaymentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{2, 0}
}

type NotificationEvent_NotificationType int32

const (
	NotificationEvent_READY                           NotificationEvent_NotificationType = 0
	NotificationEvent_INITIALIZATION_FAILED           NotificationEvent_NotificationType = 1
	NotificationEvent_ACCOUNT_CHANGED                 NotificationEvent_NotificationType = 2
	NotificationEvent_PAYMENT_SENT                    NotificationEvent_NotificationType = 3
	NotificationEvent_INVOICE_PAID                    NotificationEvent_NotificationType = 4
	NotificationEvent_ROUTING_NODE_CONNECTION_CHANGED NotificationEvent_NotificationType = 5
	NotificationEvent_LIGHTNING_SERVICE_DOWN          NotificationEvent_NotificationType = 6
	NotificationEvent_FUND_ADDRESS_CREATED            NotificationEvent_NotificationType = 7
	NotificationEvent_FUND_ADDRESS_UNSPENT_CHANGED    NotificationEvent_NotificationType = 8
	NotificationEvent_BACKUP_SUCCESS                  NotificationEvent_NotificationType = 9
	NotificationEvent_BACKUP_FAILED                   NotificationEvent_NotificationType = 10
	NotificationEvent_BACKUP_AUTH_FAILED              NotificationEvent_NotificationType = 11
	NotificationEvent_BACKUP_NODE_CONFLICT            NotificationEvent_NotificationType = 12
	NotificationEvent_BACKUP_REQUEST                  NotificationEvent_NotificationType = 13
)

var NotificationEvent_NotificationType_name = map[int32]string{
	0:  "READY",
	1:  "INITIALIZATION_FAILED",
	2:  "ACCOUNT_CHANGED",
	3:  "PAYMENT_SENT",
	4:  "INVOICE_PAID",
	5:  "ROUTING_NODE_CONNECTION_CHANGED",
	6:  "LIGHTNING_SERVICE_DOWN",
	7:  "FUND_ADDRESS_CREATED",
	8:  "FUND_ADDRESS_UNSPENT_CHANGED",
	9:  "BACKUP_SUCCESS",
	10: "BACKUP_FAILED",
	11: "BACKUP_AUTH_FAILED",
	12: "BACKUP_NODE_CONFLICT",
	13: "BACKUP_REQUEST",
}
var NotificationEvent_NotificationType_value = map[string]int32{
	"READY":                           0,
	"INITIALIZATION_FAILED":           1,
	"ACCOUNT_CHANGED":                 2,
	"PAYMENT_SENT":                    3,
	"INVOICE_PAID":                    4,
	"ROUTING_NODE_CONNECTION_CHANGED": 5,
	"LIGHTNING_SERVICE_DOWN":          6,
	"FUND_ADDRESS_CREATED":            7,
	"FUND_ADDRESS_UNSPENT_CHANGED":    8,
	"BACKUP_SUCCESS":                  9,
	"BACKUP_FAILED":                   10,
	"BACKUP_AUTH_FAILED":              11,
	"BACKUP_NODE_CONFLICT":            12,
	"BACKUP_REQUEST":                  13,
}

func (x NotificationEvent_NotificationType) String() string {
	return proto.EnumName(NotificationEvent_NotificationType_name, int32(x))
}
func (NotificationEvent_NotificationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{9, 0}
}

type FundStatusReply_FundStatus int32

const (
	FundStatusReply_NO_FUND              FundStatusReply_FundStatus = 0
	FundStatusReply_WAITING_CONFIRMATION FundStatusReply_FundStatus = 1
	FundStatusReply_CONFIRMED            FundStatusReply_FundStatus = 2
	FundStatusReply_TRANSFER_ERROR       FundStatusReply_FundStatus = 3
)

var FundStatusReply_FundStatus_name = map[int32]string{
	0: "NO_FUND",
	1: "WAITING_CONFIRMATION",
	2: "CONFIRMED",
	3: "TRANSFER_ERROR",
}
var FundStatusReply_FundStatus_value = map[string]int32{
	"NO_FUND":              0,
	"WAITING_CONFIRMATION": 1,
	"CONFIRMED":            2,
	"TRANSFER_ERROR":       3,
}

func (x FundStatusReply_FundStatus) String() string {
	return proto.EnumName(FundStatusReply_FundStatus_name, int32(x))
}
func (FundStatusReply_FundStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{14, 0}
}

type ChainStatus struct {
	BlockHeight          uint32   `protobuf:"varint,1,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	SyncedToChain        bool     `protobuf:"varint,2,opt,name=syncedToChain,proto3" json:"syncedToChain,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainStatus) Reset()         { *m = ChainStatus{} }
func (m *ChainStatus) String() string { return proto.CompactTextString(m) }
func (*ChainStatus) ProtoMessage()    {}
func (*ChainStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{0}
}
func (m *ChainStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainStatus.Unmarshal(m, b)
}
func (m *ChainStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainStatus.Marshal(b, m, deterministic)
}
func (dst *ChainStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainStatus.Merge(dst, src)
}
func (m *ChainStatus) XXX_Size() int {
	return xxx_messageInfo_ChainStatus.Size(m)
}
func (m *ChainStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ChainStatus proto.InternalMessageInfo

func (m *ChainStatus) GetBlockHeight() uint32 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *ChainStatus) GetSyncedToChain() bool {
	if m != nil {
		return m.SyncedToChain
	}
	return false
}

type Account struct {
	Id            string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Balance       int64                 `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`
	WalletBalance int64                 `protobuf:"varint,3,opt,name=walletBalance,proto3" json:"walletBalance,omitempty"`
	Status        Account_AccountStatus `protobuf:"varint,4,opt,name=status,proto3,enum=data.Account_AccountStatus" json:"status,omitempty"`
	// maximum payment this node can receive via lightning
	MaxAllowedToReceive int64 `protobuf:"varint,5,opt,name=maxAllowedToReceive,proto3" json:"maxAllowedToReceive,omitempty"`
	// maximum payment this node can pay via lightning
	MaxAllowedToPay int64 `protobuf:"varint,6,opt,name=maxAllowedToPay,proto3" json:"maxAllowedToPay,omitempty"`
	// The lightning absolute payment amount
	MaxPaymentAmount int64 `protobuf:"varint,7,opt,name=maxPaymentAmount,proto3" json:"maxPaymentAmount,omitempty"`
	// The routing node fee as reflected in the node policy
	RoutingNodeFee int64 `protobuf:"varint,8,opt,name=routingNodeFee,proto3" json:"routingNodeFee,omitempty"`
	// the state of the account, if not enabled then no automatic
	// attempt to open a channel with breez node will be made.
	Enabled bool `protobuf:"varint,9,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// maximum chan reserve accross all channels of this account.
	MaxChanReserve       int64    `protobuf:"varint,10,opt,name=maxChanReserve,proto3" json:"maxChanReserve,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{1}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Account) GetWalletBalance() int64 {
	if m != nil {
		return m.WalletBalance
	}
	return 0
}

func (m *Account) GetStatus() Account_AccountStatus {
	if m != nil {
		return m.Status
	}
	return Account_WAITING_DEPOSIT
}

func (m *Account) GetMaxAllowedToReceive() int64 {
	if m != nil {
		return m.MaxAllowedToReceive
	}
	return 0
}

func (m *Account) GetMaxAllowedToPay() int64 {
	if m != nil {
		return m.MaxAllowedToPay
	}
	return 0
}

func (m *Account) GetMaxPaymentAmount() int64 {
	if m != nil {
		return m.MaxPaymentAmount
	}
	return 0
}

func (m *Account) GetRoutingNodeFee() int64 {
	if m != nil {
		return m.RoutingNodeFee
	}
	return 0
}

func (m *Account) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Account) GetMaxChanReserve() int64 {
	if m != nil {
		return m.MaxChanReserve
	}
	return 0
}

type Payment struct {
	Type                       Payment_PaymentType `protobuf:"varint,1,opt,name=type,proto3,enum=data.Payment_PaymentType" json:"type,omitempty"`
	Amount                     int64               `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	CreationTimestamp          int64               `protobuf:"varint,4,opt,name=creationTimestamp,proto3" json:"creationTimestamp,omitempty"`
	InvoiceMemo                *InvoiceMemo        `protobuf:"bytes,6,opt,name=invoiceMemo,proto3" json:"invoiceMemo,omitempty"`
	RedeemTxID                 string              `protobuf:"bytes,7,opt,name=redeemTxID,proto3" json:"redeemTxID,omitempty"`
	PaymentHash                string              `protobuf:"bytes,8,opt,name=paymentHash,proto3" json:"paymentHash,omitempty"`
	Destination                string              `protobuf:"bytes,9,opt,name=destination,proto3" json:"destination,omitempty"`
	PendingExpirationHeight    uint32              `protobuf:"varint,10,opt,name=PendingExpirationHeight,proto3" json:"PendingExpirationHeight,omitempty"`
	PendingExpirationTimestamp int64               `protobuf:"varint,11,opt,name=PendingExpirationTimestamp,proto3" json:"PendingExpirationTimestamp,omitempty"`
	Fee                        int64               `protobuf:"varint,12,opt,name=fee,proto3" json:"fee,omitempty"`
	Preimage                   string              `protobuf:"bytes,13,opt,name=preimage,proto3" json:"preimage,omitempty"`
	XXX_NoUnkeyedLiteral       struct{}            `json:"-"`
	XXX_unrecognized           []byte              `json:"-"`
	XXX_sizecache              int32               `json:"-"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{2}
}
func (m *Payment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Payment.Unmarshal(m, b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
}
func (dst *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(dst, src)
}
func (m *Payment) XXX_Size() int {
	return xxx_messageInfo_Payment.Size(m)
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetType() Payment_PaymentType {
	if m != nil {
		return m.Type
	}
	return Payment_DEPOSIT
}

func (m *Payment) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Payment) GetCreationTimestamp() int64 {
	if m != nil {
		return m.CreationTimestamp
	}
	return 0
}

func (m *Payment) GetInvoiceMemo() *InvoiceMemo {
	if m != nil {
		return m.InvoiceMemo
	}
	return nil
}

func (m *Payment) GetRedeemTxID() string {
	if m != nil {
		return m.RedeemTxID
	}
	return ""
}

func (m *Payment) GetPaymentHash() string {
	if m != nil {
		return m.PaymentHash
	}
	return ""
}

func (m *Payment) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *Payment) GetPendingExpirationHeight() uint32 {
	if m != nil {
		return m.PendingExpirationHeight
	}
	return 0
}

func (m *Payment) GetPendingExpirationTimestamp() int64 {
	if m != nil {
		return m.PendingExpirationTimestamp
	}
	return 0
}

func (m *Payment) GetFee() int64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *Payment) GetPreimage() string {
	if m != nil {
		return m.Preimage
	}
	return ""
}

type PaymentsList struct {
	PaymentsList         []*Payment `protobuf:"bytes,1,rep,name=paymentsList,proto3" json:"paymentsList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PaymentsList) Reset()         { *m = PaymentsList{} }
func (m *PaymentsList) String() string { return proto.CompactTextString(m) }
func (*PaymentsList) ProtoMessage()    {}
func (*PaymentsList) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{3}
}
func (m *PaymentsList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentsList.Unmarshal(m, b)
}
func (m *PaymentsList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentsList.Marshal(b, m, deterministic)
}
func (dst *PaymentsList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentsList.Merge(dst, src)
}
func (m *PaymentsList) XXX_Size() int {
	return xxx_messageInfo_PaymentsList.Size(m)
}
func (m *PaymentsList) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentsList.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentsList proto.InternalMessageInfo

func (m *PaymentsList) GetPaymentsList() []*Payment {
	if m != nil {
		return m.PaymentsList
	}
	return nil
}

type PaymentResponse struct {
	PaymentError         string   `protobuf:"bytes,1,opt,name=paymentError,proto3" json:"paymentError,omitempty"`
	TraceReport          string   `protobuf:"bytes,2,opt,name=traceReport,proto3" json:"traceReport,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PaymentResponse) Reset()         { *m = PaymentResponse{} }
func (m *PaymentResponse) String() string { return proto.CompactTextString(m) }
func (*PaymentResponse) ProtoMessage()    {}
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{4}
}
func (m *PaymentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaymentResponse.Unmarshal(m, b)
}
func (m *PaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaymentResponse.Marshal(b, m, deterministic)
}
func (dst *PaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaymentResponse.Merge(dst, src)
}
func (m *PaymentResponse) XXX_Size() int {
	return xxx_messageInfo_PaymentResponse.Size(m)
}
func (m *PaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PaymentResponse proto.InternalMessageInfo

func (m *PaymentResponse) GetPaymentError() string {
	if m != nil {
		return m.PaymentError
	}
	return ""
}

func (m *PaymentResponse) GetTraceReport() string {
	if m != nil {
		return m.TraceReport
	}
	return ""
}

type SendWalletCoinsRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	SatPerByteFee        int64    `protobuf:"varint,3,opt,name=satPerByteFee,proto3" json:"satPerByteFee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendWalletCoinsRequest) Reset()         { *m = SendWalletCoinsRequest{} }
func (m *SendWalletCoinsRequest) String() string { return proto.CompactTextString(m) }
func (*SendWalletCoinsRequest) ProtoMessage()    {}
func (*SendWalletCoinsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{5}
}
func (m *SendWalletCoinsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendWalletCoinsRequest.Unmarshal(m, b)
}
func (m *SendWalletCoinsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendWalletCoinsRequest.Marshal(b, m, deterministic)
}
func (dst *SendWalletCoinsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendWalletCoinsRequest.Merge(dst, src)
}
func (m *SendWalletCoinsRequest) XXX_Size() int {
	return xxx_messageInfo_SendWalletCoinsRequest.Size(m)
}
func (m *SendWalletCoinsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendWalletCoinsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendWalletCoinsRequest proto.InternalMessageInfo

func (m *SendWalletCoinsRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SendWalletCoinsRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *SendWalletCoinsRequest) GetSatPerByteFee() int64 {
	if m != nil {
		return m.SatPerByteFee
	}
	return 0
}

type PayInvoiceRequest struct {
	Amount               int64    `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentRequest       string   `protobuf:"bytes,2,opt,name=paymentRequest,proto3" json:"paymentRequest,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayInvoiceRequest) Reset()         { *m = PayInvoiceRequest{} }
func (m *PayInvoiceRequest) String() string { return proto.CompactTextString(m) }
func (*PayInvoiceRequest) ProtoMessage()    {}
func (*PayInvoiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{6}
}
func (m *PayInvoiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayInvoiceRequest.Unmarshal(m, b)
}
func (m *PayInvoiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayInvoiceRequest.Marshal(b, m, deterministic)
}
func (dst *PayInvoiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayInvoiceRequest.Merge(dst, src)
}
func (m *PayInvoiceRequest) XXX_Size() int {
	return xxx_messageInfo_PayInvoiceRequest.Size(m)
}
func (m *PayInvoiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PayInvoiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PayInvoiceRequest proto.InternalMessageInfo

func (m *PayInvoiceRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PayInvoiceRequest) GetPaymentRequest() string {
	if m != nil {
		return m.PaymentRequest
	}
	return ""
}

type InvoiceMemo struct {
	Description          string   `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	PayeeName            string   `protobuf:"bytes,3,opt,name=payeeName,proto3" json:"payeeName,omitempty"`
	PayeeImageURL        string   `protobuf:"bytes,4,opt,name=payeeImageURL,proto3" json:"payeeImageURL,omitempty"`
	PayerName            string   `protobuf:"bytes,5,opt,name=payerName,proto3" json:"payerName,omitempty"`
	PayerImageURL        string   `protobuf:"bytes,6,opt,name=payerImageURL,proto3" json:"payerImageURL,omitempty"`
	TransferRequest      bool     `protobuf:"varint,7,opt,name=transferRequest,proto3" json:"transferRequest,omitempty"`
	Expiry               int64    `protobuf:"varint,8,opt,name=expiry,proto3" json:"expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvoiceMemo) Reset()         { *m = InvoiceMemo{} }
func (m *InvoiceMemo) String() string { return proto.CompactTextString(m) }
func (*InvoiceMemo) ProtoMessage()    {}
func (*InvoiceMemo) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{7}
}
func (m *InvoiceMemo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvoiceMemo.Unmarshal(m, b)
}
func (m *InvoiceMemo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvoiceMemo.Marshal(b, m, deterministic)
}
func (dst *InvoiceMemo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvoiceMemo.Merge(dst, src)
}
func (m *InvoiceMemo) XXX_Size() int {
	return xxx_messageInfo_InvoiceMemo.Size(m)
}
func (m *InvoiceMemo) XXX_DiscardUnknown() {
	xxx_messageInfo_InvoiceMemo.DiscardUnknown(m)
}

var xxx_messageInfo_InvoiceMemo proto.InternalMessageInfo

func (m *InvoiceMemo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *InvoiceMemo) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *InvoiceMemo) GetPayeeName() string {
	if m != nil {
		return m.PayeeName
	}
	return ""
}

func (m *InvoiceMemo) GetPayeeImageURL() string {
	if m != nil {
		return m.PayeeImageURL
	}
	return ""
}

func (m *InvoiceMemo) GetPayerName() string {
	if m != nil {
		return m.PayerName
	}
	return ""
}

func (m *InvoiceMemo) GetPayerImageURL() string {
	if m != nil {
		return m.PayerImageURL
	}
	return ""
}

func (m *InvoiceMemo) GetTransferRequest() bool {
	if m != nil {
		return m.TransferRequest
	}
	return false
}

func (m *InvoiceMemo) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

type Invoice struct {
	Memo                 *InvoiceMemo `protobuf:"bytes,1,opt,name=memo,proto3" json:"memo,omitempty"`
	Settled              bool         `protobuf:"varint,2,opt,name=settled,proto3" json:"settled,omitempty"`
	AmtPaid              int64        `protobuf:"varint,3,opt,name=amtPaid,proto3" json:"amtPaid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Invoice) Reset()         { *m = Invoice{} }
func (m *Invoice) String() string { return proto.CompactTextString(m) }
func (*Invoice) ProtoMessage()    {}
func (*Invoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{8}
}
func (m *Invoice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Invoice.Unmarshal(m, b)
}
func (m *Invoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Invoice.Marshal(b, m, deterministic)
}
func (dst *Invoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Invoice.Merge(dst, src)
}
func (m *Invoice) XXX_Size() int {
	return xxx_messageInfo_Invoice.Size(m)
}
func (m *Invoice) XXX_DiscardUnknown() {
	xxx_messageInfo_Invoice.DiscardUnknown(m)
}

var xxx_messageInfo_Invoice proto.InternalMessageInfo

func (m *Invoice) GetMemo() *InvoiceMemo {
	if m != nil {
		return m.Memo
	}
	return nil
}

func (m *Invoice) GetSettled() bool {
	if m != nil {
		return m.Settled
	}
	return false
}

func (m *Invoice) GetAmtPaid() int64 {
	if m != nil {
		return m.AmtPaid
	}
	return 0
}

type NotificationEvent struct {
	Type                 NotificationEvent_NotificationType `protobuf:"varint,1,opt,name=type,proto3,enum=data.NotificationEvent_NotificationType" json:"type,omitempty"`
	Data                 []string                           `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *NotificationEvent) Reset()         { *m = NotificationEvent{} }
func (m *NotificationEvent) String() string { return proto.CompactTextString(m) }
func (*NotificationEvent) ProtoMessage()    {}
func (*NotificationEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{9}
}
func (m *NotificationEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotificationEvent.Unmarshal(m, b)
}
func (m *NotificationEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotificationEvent.Marshal(b, m, deterministic)
}
func (dst *NotificationEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotificationEvent.Merge(dst, src)
}
func (m *NotificationEvent) XXX_Size() int {
	return xxx_messageInfo_NotificationEvent.Size(m)
}
func (m *NotificationEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_NotificationEvent.DiscardUnknown(m)
}

var xxx_messageInfo_NotificationEvent proto.InternalMessageInfo

func (m *NotificationEvent) GetType() NotificationEvent_NotificationType {
	if m != nil {
		return m.Type
	}
	return NotificationEvent_READY
}

func (m *NotificationEvent) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

type AddFundInitReply struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	MaxAllowedDeposit    int64    `protobuf:"varint,2,opt,name=maxAllowedDeposit,proto3" json:"maxAllowedDeposit,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	BackupJson           string   `protobuf:"bytes,4,opt,name=backupJson,proto3" json:"backupJson,omitempty"`
	RequiredReserve      int64    `protobuf:"varint,5,opt,name=requiredReserve,proto3" json:"requiredReserve,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFundInitReply) Reset()         { *m = AddFundInitReply{} }
func (m *AddFundInitReply) String() string { return proto.CompactTextString(m) }
func (*AddFundInitReply) ProtoMessage()    {}
func (*AddFundInitReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{10}
}
func (m *AddFundInitReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFundInitReply.Unmarshal(m, b)
}
func (m *AddFundInitReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFundInitReply.Marshal(b, m, deterministic)
}
func (dst *AddFundInitReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFundInitReply.Merge(dst, src)
}
func (m *AddFundInitReply) XXX_Size() int {
	return xxx_messageInfo_AddFundInitReply.Size(m)
}
func (m *AddFundInitReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFundInitReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddFundInitReply proto.InternalMessageInfo

func (m *AddFundInitReply) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AddFundInitReply) GetMaxAllowedDeposit() int64 {
	if m != nil {
		return m.MaxAllowedDeposit
	}
	return 0
}

func (m *AddFundInitReply) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *AddFundInitReply) GetBackupJson() string {
	if m != nil {
		return m.BackupJson
	}
	return ""
}

func (m *AddFundInitReply) GetRequiredReserve() int64 {
	if m != nil {
		return m.RequiredReserve
	}
	return 0
}

type AddFundReply struct {
	ErrorMessage         string   `protobuf:"bytes,1,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFundReply) Reset()         { *m = AddFundReply{} }
func (m *AddFundReply) String() string { return proto.CompactTextString(m) }
func (*AddFundReply) ProtoMessage()    {}
func (*AddFundReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{11}
}
func (m *AddFundReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFundReply.Unmarshal(m, b)
}
func (m *AddFundReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFundReply.Marshal(b, m, deterministic)
}
func (dst *AddFundReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFundReply.Merge(dst, src)
}
func (m *AddFundReply) XXX_Size() int {
	return xxx_messageInfo_AddFundReply.Size(m)
}
func (m *AddFundReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFundReply.DiscardUnknown(m)
}

var xxx_messageInfo_AddFundReply proto.InternalMessageInfo

func (m *AddFundReply) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type RefundRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	RefundAddress        string   `protobuf:"bytes,2,opt,name=refundAddress,proto3" json:"refundAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefundRequest) Reset()         { *m = RefundRequest{} }
func (m *RefundRequest) String() string { return proto.CompactTextString(m) }
func (*RefundRequest) ProtoMessage()    {}
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{12}
}
func (m *RefundRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefundRequest.Unmarshal(m, b)
}
func (m *RefundRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefundRequest.Marshal(b, m, deterministic)
}
func (dst *RefundRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefundRequest.Merge(dst, src)
}
func (m *RefundRequest) XXX_Size() int {
	return xxx_messageInfo_RefundRequest.Size(m)
}
func (m *RefundRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefundRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefundRequest proto.InternalMessageInfo

func (m *RefundRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RefundRequest) GetRefundAddress() string {
	if m != nil {
		return m.RefundAddress
	}
	return ""
}

type AddFundError struct {
	ErrorMessage         string   `protobuf:"bytes,1,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	FundsExceededLimit   bool     `protobuf:"varint,2,opt,name=FundsExceededLimit,proto3" json:"FundsExceededLimit,omitempty"`
	LockHeight           uint32   `protobuf:"varint,3,opt,name=lockHeight,proto3" json:"lockHeight,omitempty"`
	HoursToUnlock        float32  `protobuf:"fixed32,4,opt,name=hoursToUnlock,proto3" json:"hoursToUnlock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFundError) Reset()         { *m = AddFundError{} }
func (m *AddFundError) String() string { return proto.CompactTextString(m) }
func (*AddFundError) ProtoMessage()    {}
func (*AddFundError) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{13}
}
func (m *AddFundError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFundError.Unmarshal(m, b)
}
func (m *AddFundError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFundError.Marshal(b, m, deterministic)
}
func (dst *AddFundError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFundError.Merge(dst, src)
}
func (m *AddFundError) XXX_Size() int {
	return xxx_messageInfo_AddFundError.Size(m)
}
func (m *AddFundError) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFundError.DiscardUnknown(m)
}

var xxx_messageInfo_AddFundError proto.InternalMessageInfo

func (m *AddFundError) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *AddFundError) GetFundsExceededLimit() bool {
	if m != nil {
		return m.FundsExceededLimit
	}
	return false
}

func (m *AddFundError) GetLockHeight() uint32 {
	if m != nil {
		return m.LockHeight
	}
	return 0
}

func (m *AddFundError) GetHoursToUnlock() float32 {
	if m != nil {
		return m.HoursToUnlock
	}
	return 0
}

type FundStatusReply struct {
	Status               FundStatusReply_FundStatus `protobuf:"varint,1,opt,name=status,proto3,enum=data.FundStatusReply_FundStatus" json:"status,omitempty"`
	Error                *AddFundError              `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *FundStatusReply) Reset()         { *m = FundStatusReply{} }
func (m *FundStatusReply) String() string { return proto.CompactTextString(m) }
func (*FundStatusReply) ProtoMessage()    {}
func (*FundStatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{14}
}
func (m *FundStatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FundStatusReply.Unmarshal(m, b)
}
func (m *FundStatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FundStatusReply.Marshal(b, m, deterministic)
}
func (dst *FundStatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FundStatusReply.Merge(dst, src)
}
func (m *FundStatusReply) XXX_Size() int {
	return xxx_messageInfo_FundStatusReply.Size(m)
}
func (m *FundStatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FundStatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_FundStatusReply proto.InternalMessageInfo

func (m *FundStatusReply) GetStatus() FundStatusReply_FundStatus {
	if m != nil {
		return m.Status
	}
	return FundStatusReply_NO_FUND
}

func (m *FundStatusReply) GetError() *AddFundError {
	if m != nil {
		return m.Error
	}
	return nil
}

type RemoveFundRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFundRequest) Reset()         { *m = RemoveFundRequest{} }
func (m *RemoveFundRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFundRequest) ProtoMessage()    {}
func (*RemoveFundRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{15}
}
func (m *RemoveFundRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFundRequest.Unmarshal(m, b)
}
func (m *RemoveFundRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFundRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveFundRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFundRequest.Merge(dst, src)
}
func (m *RemoveFundRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFundRequest.Size(m)
}
func (m *RemoveFundRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFundRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFundRequest proto.InternalMessageInfo

func (m *RemoveFundRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RemoveFundRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type RemoveFundReply struct {
	Txid                 string   `protobuf:"bytes,1,opt,name=txid,proto3" json:"txid,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFundReply) Reset()         { *m = RemoveFundReply{} }
func (m *RemoveFundReply) String() string { return proto.CompactTextString(m) }
func (*RemoveFundReply) ProtoMessage()    {}
func (*RemoveFundReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{16}
}
func (m *RemoveFundReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFundReply.Unmarshal(m, b)
}
func (m *RemoveFundReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFundReply.Marshal(b, m, deterministic)
}
func (dst *RemoveFundReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFundReply.Merge(dst, src)
}
func (m *RemoveFundReply) XXX_Size() int {
	return xxx_messageInfo_RemoveFundReply.Size(m)
}
func (m *RemoveFundReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFundReply.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFundReply proto.InternalMessageInfo

func (m *RemoveFundReply) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *RemoveFundReply) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type SwapAddressInfo struct {
	Address                 string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PaymentHash             string   `protobuf:"bytes,2,opt,name=PaymentHash,proto3" json:"PaymentHash,omitempty"`
	ConfirmedAmount         int64    `protobuf:"varint,3,opt,name=ConfirmedAmount,proto3" json:"ConfirmedAmount,omitempty"`
	ConfirmedTransactionIds []string `protobuf:"bytes,4,rep,name=ConfirmedTransactionIds,proto3" json:"ConfirmedTransactionIds,omitempty"`
	PaidAmount              int64    `protobuf:"varint,5,opt,name=PaidAmount,proto3" json:"PaidAmount,omitempty"`
	LockHeight              uint32   `protobuf:"varint,6,opt,name=lockHeight,proto3" json:"lockHeight,omitempty"`
	ErrorMessage            string   `protobuf:"bytes,7,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	LastRefundTxID          string   `protobuf:"bytes,8,opt,name=lastRefundTxID,proto3" json:"lastRefundTxID,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *SwapAddressInfo) Reset()         { *m = SwapAddressInfo{} }
func (m *SwapAddressInfo) String() string { return proto.CompactTextString(m) }
func (*SwapAddressInfo) ProtoMessage()    {}
func (*SwapAddressInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{17}
}
func (m *SwapAddressInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwapAddressInfo.Unmarshal(m, b)
}
func (m *SwapAddressInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwapAddressInfo.Marshal(b, m, deterministic)
}
func (dst *SwapAddressInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwapAddressInfo.Merge(dst, src)
}
func (m *SwapAddressInfo) XXX_Size() int {
	return xxx_messageInfo_SwapAddressInfo.Size(m)
}
func (m *SwapAddressInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SwapAddressInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SwapAddressInfo proto.InternalMessageInfo

func (m *SwapAddressInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SwapAddressInfo) GetPaymentHash() string {
	if m != nil {
		return m.PaymentHash
	}
	return ""
}

func (m *SwapAddressInfo) GetConfirmedAmount() int64 {
	if m != nil {
		return m.ConfirmedAmount
	}
	return 0
}

func (m *SwapAddressInfo) GetConfirmedTransactionIds() []string {
	if m != nil {
		return m.ConfirmedTransactionIds
	}
	return nil
}

func (m *SwapAddressInfo) GetPaidAmount() int64 {
	if m != nil {
		return m.PaidAmount
	}
	return 0
}

func (m *SwapAddressInfo) GetLockHeight() uint32 {
	if m != nil {
		return m.LockHeight
	}
	return 0
}

func (m *SwapAddressInfo) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *SwapAddressInfo) GetLastRefundTxID() string {
	if m != nil {
		return m.LastRefundTxID
	}
	return ""
}

type SwapAddressList struct {
	Addresses            []*SwapAddressInfo `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SwapAddressList) Reset()         { *m = SwapAddressList{} }
func (m *SwapAddressList) String() string { return proto.CompactTextString(m) }
func (*SwapAddressList) ProtoMessage()    {}
func (*SwapAddressList) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{18}
}
func (m *SwapAddressList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SwapAddressList.Unmarshal(m, b)
}
func (m *SwapAddressList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SwapAddressList.Marshal(b, m, deterministic)
}
func (dst *SwapAddressList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SwapAddressList.Merge(dst, src)
}
func (m *SwapAddressList) XXX_Size() int {
	return xxx_messageInfo_SwapAddressList.Size(m)
}
func (m *SwapAddressList) XXX_DiscardUnknown() {
	xxx_messageInfo_SwapAddressList.DiscardUnknown(m)
}

var xxx_messageInfo_SwapAddressList proto.InternalMessageInfo

func (m *SwapAddressList) GetAddresses() []*SwapAddressInfo {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type CreateRatchetSessionRequest struct {
	Secret               string   `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	RemotePubKey         string   `protobuf:"bytes,2,opt,name=remotePubKey,proto3" json:"remotePubKey,omitempty"`
	SessionID            string   `protobuf:"bytes,3,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Expiry               uint64   `protobuf:"varint,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRatchetSessionRequest) Reset()         { *m = CreateRatchetSessionRequest{} }
func (m *CreateRatchetSessionRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRatchetSessionRequest) ProtoMessage()    {}
func (*CreateRatchetSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{19}
}
func (m *CreateRatchetSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRatchetSessionRequest.Unmarshal(m, b)
}
func (m *CreateRatchetSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRatchetSessionRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRatchetSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRatchetSessionRequest.Merge(dst, src)
}
func (m *CreateRatchetSessionRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRatchetSessionRequest.Size(m)
}
func (m *CreateRatchetSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRatchetSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRatchetSessionRequest proto.InternalMessageInfo

func (m *CreateRatchetSessionRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *CreateRatchetSessionRequest) GetRemotePubKey() string {
	if m != nil {
		return m.RemotePubKey
	}
	return ""
}

func (m *CreateRatchetSessionRequest) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *CreateRatchetSessionRequest) GetExpiry() uint64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

type CreateRatchetSessionReply struct {
	SessionID            string   `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Secret               string   `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	PubKey               string   `protobuf:"bytes,3,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRatchetSessionReply) Reset()         { *m = CreateRatchetSessionReply{} }
func (m *CreateRatchetSessionReply) String() string { return proto.CompactTextString(m) }
func (*CreateRatchetSessionReply) ProtoMessage()    {}
func (*CreateRatchetSessionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{20}
}
func (m *CreateRatchetSessionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRatchetSessionReply.Unmarshal(m, b)
}
func (m *CreateRatchetSessionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRatchetSessionReply.Marshal(b, m, deterministic)
}
func (dst *CreateRatchetSessionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRatchetSessionReply.Merge(dst, src)
}
func (m *CreateRatchetSessionReply) XXX_Size() int {
	return xxx_messageInfo_CreateRatchetSessionReply.Size(m)
}
func (m *CreateRatchetSessionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRatchetSessionReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRatchetSessionReply proto.InternalMessageInfo

func (m *CreateRatchetSessionReply) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *CreateRatchetSessionReply) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *CreateRatchetSessionReply) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

type RatchetSessionInfoReply struct {
	SessionID            string   `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Initiated            bool     `protobuf:"varint,2,opt,name=initiated,proto3" json:"initiated,omitempty"`
	UserInfo             string   `protobuf:"bytes,3,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RatchetSessionInfoReply) Reset()         { *m = RatchetSessionInfoReply{} }
func (m *RatchetSessionInfoReply) String() string { return proto.CompactTextString(m) }
func (*RatchetSessionInfoReply) ProtoMessage()    {}
func (*RatchetSessionInfoReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{21}
}
func (m *RatchetSessionInfoReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RatchetSessionInfoReply.Unmarshal(m, b)
}
func (m *RatchetSessionInfoReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RatchetSessionInfoReply.Marshal(b, m, deterministic)
}
func (dst *RatchetSessionInfoReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RatchetSessionInfoReply.Merge(dst, src)
}
func (m *RatchetSessionInfoReply) XXX_Size() int {
	return xxx_messageInfo_RatchetSessionInfoReply.Size(m)
}
func (m *RatchetSessionInfoReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RatchetSessionInfoReply.DiscardUnknown(m)
}

var xxx_messageInfo_RatchetSessionInfoReply proto.InternalMessageInfo

func (m *RatchetSessionInfoReply) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *RatchetSessionInfoReply) GetInitiated() bool {
	if m != nil {
		return m.Initiated
	}
	return false
}

func (m *RatchetSessionInfoReply) GetUserInfo() string {
	if m != nil {
		return m.UserInfo
	}
	return ""
}

type RatchetSessionSetInfoRequest struct {
	SessionID            string   `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	UserInfo             string   `protobuf:"bytes,2,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RatchetSessionSetInfoRequest) Reset()         { *m = RatchetSessionSetInfoRequest{} }
func (m *RatchetSessionSetInfoRequest) String() string { return proto.CompactTextString(m) }
func (*RatchetSessionSetInfoRequest) ProtoMessage()    {}
func (*RatchetSessionSetInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{22}
}
func (m *RatchetSessionSetInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RatchetSessionSetInfoRequest.Unmarshal(m, b)
}
func (m *RatchetSessionSetInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RatchetSessionSetInfoRequest.Marshal(b, m, deterministic)
}
func (dst *RatchetSessionSetInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RatchetSessionSetInfoRequest.Merge(dst, src)
}
func (m *RatchetSessionSetInfoRequest) XXX_Size() int {
	return xxx_messageInfo_RatchetSessionSetInfoRequest.Size(m)
}
func (m *RatchetSessionSetInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RatchetSessionSetInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RatchetSessionSetInfoRequest proto.InternalMessageInfo

func (m *RatchetSessionSetInfoRequest) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *RatchetSessionSetInfoRequest) GetUserInfo() string {
	if m != nil {
		return m.UserInfo
	}
	return ""
}

type RatchetEncryptRequest struct {
	SessionID            string   `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RatchetEncryptRequest) Reset()         { *m = RatchetEncryptRequest{} }
func (m *RatchetEncryptRequest) String() string { return proto.CompactTextString(m) }
func (*RatchetEncryptRequest) ProtoMessage()    {}
func (*RatchetEncryptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{23}
}
func (m *RatchetEncryptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RatchetEncryptRequest.Unmarshal(m, b)
}
func (m *RatchetEncryptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RatchetEncryptRequest.Marshal(b, m, deterministic)
}
func (dst *RatchetEncryptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RatchetEncryptRequest.Merge(dst, src)
}
func (m *RatchetEncryptRequest) XXX_Size() int {
	return xxx_messageInfo_RatchetEncryptRequest.Size(m)
}
func (m *RatchetEncryptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RatchetEncryptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RatchetEncryptRequest proto.InternalMessageInfo

func (m *RatchetEncryptRequest) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *RatchetEncryptRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RatchetDecryptRequest struct {
	SessionID            string   `protobuf:"bytes,1,opt,name=sessionID,proto3" json:"sessionID,omitempty"`
	EncryptedMessage     string   `protobuf:"bytes,2,opt,name=encryptedMessage,proto3" json:"encryptedMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RatchetDecryptRequest) Reset()         { *m = RatchetDecryptRequest{} }
func (m *RatchetDecryptRequest) String() string { return proto.CompactTextString(m) }
func (*RatchetDecryptRequest) ProtoMessage()    {}
func (*RatchetDecryptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{24}
}
func (m *RatchetDecryptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RatchetDecryptRequest.Unmarshal(m, b)
}
func (m *RatchetDecryptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RatchetDecryptRequest.Marshal(b, m, deterministic)
}
func (dst *RatchetDecryptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RatchetDecryptRequest.Merge(dst, src)
}
func (m *RatchetDecryptRequest) XXX_Size() int {
	return xxx_messageInfo_RatchetDecryptRequest.Size(m)
}
func (m *RatchetDecryptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RatchetDecryptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RatchetDecryptRequest proto.InternalMessageInfo

func (m *RatchetDecryptRequest) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *RatchetDecryptRequest) GetEncryptedMessage() string {
	if m != nil {
		return m.EncryptedMessage
	}
	return ""
}

type BootstrapFilesRequest struct {
	WorkingDir           string   `protobuf:"bytes,1,opt,name=WorkingDir,proto3" json:"WorkingDir,omitempty"`
	FullPaths            []string `protobuf:"bytes,2,rep,name=FullPaths,proto3" json:"FullPaths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BootstrapFilesRequest) Reset()         { *m = BootstrapFilesRequest{} }
func (m *BootstrapFilesRequest) String() string { return proto.CompactTextString(m) }
func (*BootstrapFilesRequest) ProtoMessage()    {}
func (*BootstrapFilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{25}
}
func (m *BootstrapFilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BootstrapFilesRequest.Unmarshal(m, b)
}
func (m *BootstrapFilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BootstrapFilesRequest.Marshal(b, m, deterministic)
}
func (dst *BootstrapFilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BootstrapFilesRequest.Merge(dst, src)
}
func (m *BootstrapFilesRequest) XXX_Size() int {
	return xxx_messageInfo_BootstrapFilesRequest.Size(m)
}
func (m *BootstrapFilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BootstrapFilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BootstrapFilesRequest proto.InternalMessageInfo

func (m *BootstrapFilesRequest) GetWorkingDir() string {
	if m != nil {
		return m.WorkingDir
	}
	return ""
}

func (m *BootstrapFilesRequest) GetFullPaths() []string {
	if m != nil {
		return m.FullPaths
	}
	return nil
}

type Peers struct {
	IsDefault            bool     `protobuf:"varint,1,opt,name=isDefault,proto3" json:"isDefault,omitempty"`
	Peer                 []string `protobuf:"bytes,2,rep,name=peer,proto3" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Peers) Reset()         { *m = Peers{} }
func (m *Peers) String() string { return proto.CompactTextString(m) }
func (*Peers) ProtoMessage()    {}
func (*Peers) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{26}
}
func (m *Peers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Peers.Unmarshal(m, b)
}
func (m *Peers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Peers.Marshal(b, m, deterministic)
}
func (dst *Peers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Peers.Merge(dst, src)
}
func (m *Peers) XXX_Size() int {
	return xxx_messageInfo_Peers.Size(m)
}
func (m *Peers) XXX_DiscardUnknown() {
	xxx_messageInfo_Peers.DiscardUnknown(m)
}

var xxx_messageInfo_Peers proto.InternalMessageInfo

func (m *Peers) GetIsDefault() bool {
	if m != nil {
		return m.IsDefault
	}
	return false
}

func (m *Peers) GetPeer() []string {
	if m != nil {
		return m.Peer
	}
	return nil
}

type Rate struct {
	Coin                 string   `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	Value                float64  `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rate) Reset()         { *m = Rate{} }
func (m *Rate) String() string { return proto.CompactTextString(m) }
func (*Rate) ProtoMessage()    {}
func (*Rate) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{27}
}
func (m *Rate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rate.Unmarshal(m, b)
}
func (m *Rate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rate.Marshal(b, m, deterministic)
}
func (dst *Rate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rate.Merge(dst, src)
}
func (m *Rate) XXX_Size() int {
	return xxx_messageInfo_Rate.Size(m)
}
func (m *Rate) XXX_DiscardUnknown() {
	xxx_messageInfo_Rate.DiscardUnknown(m)
}

var xxx_messageInfo_Rate proto.InternalMessageInfo

func (m *Rate) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

func (m *Rate) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Rates struct {
	Rates                []*Rate  `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rates) Reset()         { *m = Rates{} }
func (m *Rates) String() string { return proto.CompactTextString(m) }
func (*Rates) ProtoMessage()    {}
func (*Rates) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_93c9b8dbef806640, []int{28}
}
func (m *Rates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rates.Unmarshal(m, b)
}
func (m *Rates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rates.Marshal(b, m, deterministic)
}
func (dst *Rates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rates.Merge(dst, src)
}
func (m *Rates) XXX_Size() int {
	return xxx_messageInfo_Rates.Size(m)
}
func (m *Rates) XXX_DiscardUnknown() {
	xxx_messageInfo_Rates.DiscardUnknown(m)
}

var xxx_messageInfo_Rates proto.InternalMessageInfo

func (m *Rates) GetRates() []*Rate {
	if m != nil {
		return m.Rates
	}
	return nil
}

func init() {
	proto.RegisterType((*ChainStatus)(nil), "data.ChainStatus")
	proto.RegisterType((*Account)(nil), "data.Account")
	proto.RegisterType((*Payment)(nil), "data.Payment")
	proto.RegisterType((*PaymentsList)(nil), "data.PaymentsList")
	proto.RegisterType((*PaymentResponse)(nil), "data.PaymentResponse")
	proto.RegisterType((*SendWalletCoinsRequest)(nil), "data.SendWalletCoinsRequest")
	proto.RegisterType((*PayInvoiceRequest)(nil), "data.PayInvoiceRequest")
	proto.RegisterType((*InvoiceMemo)(nil), "data.InvoiceMemo")
	proto.RegisterType((*Invoice)(nil), "data.Invoice")
	proto.RegisterType((*NotificationEvent)(nil), "data.NotificationEvent")
	proto.RegisterType((*AddFundInitReply)(nil), "data.AddFundInitReply")
	proto.RegisterType((*AddFundReply)(nil), "data.AddFundReply")
	proto.RegisterType((*RefundRequest)(nil), "data.RefundRequest")
	proto.RegisterType((*AddFundError)(nil), "data.AddFundError")
	proto.RegisterType((*FundStatusReply)(nil), "data.FundStatusReply")
	proto.RegisterType((*RemoveFundRequest)(nil), "data.RemoveFundRequest")
	proto.RegisterType((*RemoveFundReply)(nil), "data.RemoveFundReply")
	proto.RegisterType((*SwapAddressInfo)(nil), "data.SwapAddressInfo")
	proto.RegisterType((*SwapAddressList)(nil), "data.SwapAddressList")
	proto.RegisterType((*CreateRatchetSessionRequest)(nil), "data.CreateRatchetSessionRequest")
	proto.RegisterType((*CreateRatchetSessionReply)(nil), "data.CreateRatchetSessionReply")
	proto.RegisterType((*RatchetSessionInfoReply)(nil), "data.RatchetSessionInfoReply")
	proto.RegisterType((*RatchetSessionSetInfoRequest)(nil), "data.RatchetSessionSetInfoRequest")
	proto.RegisterType((*RatchetEncryptRequest)(nil), "data.RatchetEncryptRequest")
	proto.RegisterType((*RatchetDecryptRequest)(nil), "data.RatchetDecryptRequest")
	proto.RegisterType((*BootstrapFilesRequest)(nil), "data.BootstrapFilesRequest")
	proto.RegisterType((*Peers)(nil), "data.Peers")
	proto.RegisterType((*Rate)(nil), "data.rate")
	proto.RegisterType((*Rates)(nil), "data.Rates")
	proto.RegisterEnum("data.Account_AccountStatus", Account_AccountStatus_name, Account_AccountStatus_value)
	proto.RegisterEnum("data.Payment_PaymentType", Payment_PaymentType_name, Payment_PaymentType_value)
	proto.RegisterEnum("data.NotificationEvent_NotificationType", NotificationEvent_NotificationType_name, NotificationEvent_NotificationType_value)
	proto.RegisterEnum("data.FundStatusReply_FundStatus", FundStatusReply_FundStatus_name, FundStatusReply_FundStatus_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_messages_93c9b8dbef806640) }

var fileDescriptor_messages_93c9b8dbef806640 = []byte{
	// 1854 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0xdd, 0x72, 0xdb, 0xc6,
	0x15, 0x36, 0x48, 0x4a, 0x14, 0x0f, 0x45, 0x0a, 0xda, 0xc4, 0x0e, 0xfd, 0x33, 0x89, 0x06, 0x4d,
	0x3d, 0x6a, 0x26, 0xf5, 0xa4, 0xf2, 0x4d, 0x3a, 0xd3, 0xe9, 0x0c, 0x44, 0x80, 0x16, 0x1a, 0x19,
	0x64, 0x97, 0xa0, 0xd4, 0xe4, 0x86, 0xb3, 0x22, 0x8e, 0x24, 0x8c, 0x89, 0x1f, 0x03, 0x4b, 0x59,
	0xbc, 0xee, 0x7d, 0x3b, 0x79, 0x8b, 0xbe, 0x44, 0xaf, 0x7a, 0xd3, 0x9b, 0x3e, 0x41, 0x5f, 0xa6,
	0xb3, 0x8b, 0x05, 0x09, 0x50, 0x92, 0xeb, 0x5c, 0x89, 0xfb, 0x9d, 0x83, 0xb3, 0x67, 0xcf, 0xef,
	0x67, 0x43, 0x37, 0xc4, 0x2c, 0x63, 0x57, 0x98, 0xbd, 0x4a, 0xd2, 0x98, 0xc7, 0xa4, 0xe1, 0x33,
	0xce, 0x8c, 0x09, 0xb4, 0xfb, 0xd7, 0x2c, 0x88, 0xc6, 0x9c, 0xf1, 0x45, 0x46, 0x0e, 0xa0, 0x7d,
	0x31, 0x8f, 0x67, 0xef, 0x4e, 0x30, 0xb8, 0xba, 0xe6, 0x3d, 0xed, 0x40, 0x3b, 0xec, 0xd0, 0x32,
	0x44, 0xbe, 0x86, 0x4e, 0xb6, 0x8c, 0x66, 0xe8, 0x7b, 0xb1, 0xfc, 0xb0, 0x57, 0x3b, 0xd0, 0x0e,
	0x77, 0x68, 0x15, 0x34, 0x7e, 0x6e, 0x40, 0xd3, 0x9c, 0xcd, 0xe2, 0x45, 0xc4, 0x49, 0x17, 0x6a,
	0x81, 0x2f, 0x4d, 0xb5, 0x68, 0x2d, 0xf0, 0x49, 0x0f, 0x9a, 0x17, 0x6c, 0xce, 0xa2, 0x19, 0xca,
	0x6f, 0xeb, 0xb4, 0x38, 0x0a, 0xdb, 0x1f, 0xd8, 0x7c, 0x8e, 0xfc, 0x58, 0xc9, 0xeb, 0x52, 0x5e,
	0x05, 0xc9, 0x6b, 0xd8, 0xce, 0xa4, 0xb7, 0xbd, 0xc6, 0x81, 0x76, 0xd8, 0x3d, 0x7a, 0xfe, 0x4a,
	0xbc, 0xe4, 0x95, 0xba, 0xae, 0xf8, 0x9b, 0x3f, 0x88, 0x2a, 0x55, 0xf2, 0x1d, 0x7c, 0x16, 0xb2,
	0x5b, 0x73, 0x3e, 0x8f, 0x3f, 0x08, 0x2f, 0x29, 0xce, 0x30, 0xb8, 0xc1, 0xde, 0x96, 0xbc, 0xe0,
	0x3e, 0x11, 0x39, 0x84, 0xbd, 0x32, 0x3c, 0x62, 0xcb, 0xde, 0xb6, 0xd4, 0xde, 0x84, 0xc9, 0x37,
	0xa0, 0x87, 0xec, 0x76, 0xc4, 0x96, 0x21, 0x46, 0xdc, 0x0c, 0xc5, 0xed, 0xbd, 0xa6, 0x54, 0xbd,
	0x83, 0x93, 0x97, 0xd0, 0x4d, 0xe3, 0x05, 0x0f, 0xa2, 0x2b, 0x37, 0xf6, 0x71, 0x80, 0xd8, 0xdb,
	0x91, 0x9a, 0x1b, 0xa8, 0x08, 0x12, 0x46, 0xec, 0x62, 0x8e, 0x7e, 0xaf, 0x25, 0x03, 0x5c, 0x1c,
	0x85, 0x85, 0x90, 0xdd, 0xf6, 0xaf, 0x59, 0x44, 0x31, 0xc3, 0xf4, 0x06, 0x7b, 0x90, 0x5b, 0xa8,
	0xa2, 0xc6, 0xdf, 0x34, 0xe8, 0x54, 0x62, 0x41, 0x3e, 0x83, 0xbd, 0x73, 0xd3, 0xf1, 0x1c, 0xf7,
	0xcd, 0xd4, 0xb2, 0x47, 0xc3, 0xb1, 0xe3, 0xe9, 0x8f, 0xc8, 0x01, 0xbc, 0xd8, 0x00, 0xa7, 0xfd,
	0xa1, 0x3b, 0x70, 0xe8, 0x5b, 0xd3, 0x73, 0x86, 0xae, 0xae, 0x91, 0xaf, 0xe0, 0xf9, 0x88, 0x0e,
	0xfb, 0xf6, 0x78, 0x2c, 0x94, 0x8e, 0xa9, 0x6d, 0xff, 0x24, 0x54, 0x5c, 0xbb, 0x2f, 0x15, 0x6a,
	0xe4, 0x29, 0x3c, 0x2e, 0x29, 0x9c, 0x3b, 0xde, 0x89, 0x45, 0xcd, 0x73, 0xf3, 0x54, 0xaf, 0x13,
	0x80, 0x6d, 0xb3, 0xef, 0x39, 0x67, 0xb6, 0xde, 0x30, 0xfe, 0xda, 0x80, 0xa6, 0x0a, 0x06, 0xf9,
	0x2d, 0x34, 0xf8, 0x32, 0x41, 0x59, 0x15, 0xdd, 0xa3, 0xa7, 0x79, 0x06, 0x95, 0xb0, 0xf8, 0xeb,
	0x2d, 0x13, 0xa4, 0x52, 0x8d, 0x3c, 0x81, 0x6d, 0x96, 0xc7, 0x35, 0xaf, 0x08, 0x75, 0x22, 0xdf,
	0xc2, 0xfe, 0x2c, 0x45, 0xc6, 0x83, 0x38, 0xf2, 0x82, 0x10, 0x33, 0xce, 0xc2, 0x44, 0x56, 0x45,
	0x9d, 0xde, 0x15, 0x90, 0xd7, 0xd0, 0x0e, 0xa2, 0x9b, 0x38, 0x98, 0xe1, 0x5b, 0x0c, 0x63, 0x99,
	0xcd, 0xf6, 0xd1, 0x7e, 0x7e, 0xb7, 0xb3, 0x16, 0xd0, 0xb2, 0x16, 0xf9, 0x12, 0x20, 0x45, 0x1f,
	0x31, 0xf4, 0x6e, 0x1d, 0x4b, 0xa6, 0xb5, 0x45, 0x4b, 0x88, 0xe8, 0x98, 0x24, 0xf7, 0xf7, 0x84,
	0x65, 0xd7, 0x32, 0x9b, 0x2d, 0x5a, 0x86, 0x84, 0x86, 0x8f, 0x19, 0x0f, 0x22, 0xe9, 0x8e, 0x4c,
	0x67, 0x8b, 0x96, 0x21, 0xf2, 0x3d, 0x7c, 0x31, 0xc2, 0xc8, 0x0f, 0xa2, 0x2b, 0xfb, 0x36, 0x09,
	0x52, 0x09, 0xaa, 0x0e, 0x04, 0xd9, 0x81, 0x0f, 0x89, 0xc9, 0x1f, 0xe1, 0xd9, 0x1d, 0xd1, 0x3a,
	0x12, 0x6d, 0x19, 0x89, 0x8f, 0x68, 0x10, 0x1d, 0xea, 0x97, 0x88, 0xbd, 0x5d, 0xa9, 0x28, 0x7e,
	0x92, 0x67, 0xb0, 0x93, 0xa4, 0x18, 0x84, 0xec, 0x0a, 0x7b, 0x1d, 0xe9, 0xea, 0xea, 0x6c, 0x1c,
	0x43, 0xbb, 0x94, 0x1b, 0xd2, 0x86, 0xe6, 0xba, 0x8e, 0xba, 0x00, 0xa5, 0xcc, 0x6b, 0x64, 0x07,
	0x1a, 0x63, 0xdb, 0xf5, 0xf4, 0x1a, 0xd9, 0x85, 0x1d, 0x6a, 0xf7, 0x6d, 0xe7, 0xcc, 0xb6, 0xf4,
	0xba, 0x61, 0xc2, 0xae, 0xb2, 0x91, 0x9d, 0x06, 0x19, 0x27, 0xbf, 0x83, 0xdd, 0xa4, 0x74, 0xee,
	0x69, 0x07, 0xf5, 0xc3, 0xf6, 0x51, 0xa7, 0x52, 0x11, 0xb4, 0xa2, 0x62, 0x9c, 0xc3, 0x5e, 0x21,
	0xc0, 0x2c, 0x89, 0xa3, 0x0c, 0x89, 0xb1, 0xb2, 0x62, 0xa7, 0x69, 0x9c, 0xaa, 0x69, 0x53, 0xc1,
	0x44, 0x1e, 0x78, 0xca, 0x66, 0x48, 0x31, 0x89, 0x53, 0x2e, 0x67, 0x4f, 0x8b, 0x96, 0x21, 0x23,
	0x81, 0x27, 0x63, 0x8c, 0xfc, 0x73, 0x39, 0x6e, 0xfa, 0x71, 0x10, 0x65, 0x14, 0xdf, 0x2f, 0x30,
	0xe3, 0xa2, 0x1d, 0x99, 0xef, 0xa7, 0x98, 0x65, 0xca, 0x74, 0x71, 0x2c, 0x95, 0x66, 0xad, 0x52,
	0x9a, 0x62, 0x4e, 0x32, 0x3e, 0xc2, 0xf4, 0x78, 0xc9, 0x65, 0x9f, 0xab, 0x59, 0x56, 0x01, 0x8d,
	0x31, 0xec, 0x8f, 0xd8, 0x52, 0x15, 0x5f, 0x71, 0xd9, 0xda, 0xa4, 0x56, 0x31, 0xf9, 0x12, 0xba,
	0x49, 0xf1, 0x6e, 0xa9, 0xa9, 0xde, 0xb0, 0x81, 0x1a, 0x3f, 0xd7, 0xa0, 0x5d, 0xaa, 0x67, 0x55,
	0x80, 0xb3, 0x34, 0x48, 0x64, 0x01, 0x6a, 0xab, 0x02, 0x2c, 0xa0, 0x07, 0x1f, 0xf1, 0x02, 0x5a,
	0x09, 0x5b, 0x22, 0xba, 0x2c, 0xcc, 0x1f, 0xd0, 0xa2, 0x6b, 0x40, 0x3c, 0x51, 0x1e, 0x1c, 0x51,
	0x1c, 0x13, 0x7a, 0x2a, 0x3b, 0xaf, 0x45, 0xab, 0x60, 0x61, 0x23, 0x95, 0x36, 0xb6, 0xd6, 0x36,
	0xd2, 0xb2, 0x8d, 0x74, 0x65, 0x63, 0x7b, 0x6d, 0x63, 0x05, 0x8a, 0x59, 0xcc, 0x53, 0x16, 0x65,
	0x97, 0x98, 0x16, 0x4f, 0x6f, 0xca, 0xa9, 0xb8, 0x09, 0x8b, 0x97, 0xa0, 0xa8, 0xf3, 0xa5, 0x9a,
	0xab, 0xea, 0x64, 0xf8, 0xd0, 0x54, 0x21, 0x21, 0xbf, 0x86, 0x46, 0x28, 0xfa, 0x5f, 0x7b, 0xa8,
	0xff, 0xa5, 0x58, 0xa4, 0x3c, 0x43, 0xce, 0xc5, 0x04, 0xce, 0x57, 0x5c, 0x71, 0x94, 0xc5, 0x10,
	0xf2, 0x11, 0x0b, 0x7c, 0x95, 0xd4, 0xe2, 0x68, 0xfc, 0xab, 0x0e, 0xfb, 0x6e, 0xcc, 0x83, 0xcb,
	0x60, 0x26, 0x1b, 0xcd, 0xbe, 0x11, 0xc3, 0xee, 0x0f, 0x95, 0x61, 0x77, 0x98, 0x5f, 0x78, 0x47,
	0xad, 0x82, 0x94, 0x66, 0x1f, 0x01, 0xb9, 0xa9, 0x7b, 0xb5, 0x83, 0xfa, 0x61, 0x8b, 0xe6, 0x5b,
	0xfb, 0xbf, 0x35, 0xd0, 0x37, 0xd5, 0x49, 0x0b, 0xb6, 0xa8, 0x6d, 0x5a, 0x3f, 0xea, 0x8f, 0xc4,
	0x44, 0x76, 0x5c, 0xc7, 0x73, 0xcc, 0x53, 0xe7, 0x27, 0x39, 0xc6, 0xa7, 0x03, 0xd3, 0x39, 0xb5,
	0x2d, 0x5d, 0x13, 0x4b, 0xc0, 0xec, 0xf7, 0x87, 0x13, 0xd7, 0x9b, 0xf6, 0x4f, 0x4c, 0xf7, 0x8d,
	0x6d, 0xe9, 0x35, 0xa2, 0xc3, 0xee, 0xc8, 0xfc, 0xf1, 0xad, 0xed, 0x7a, 0x53, 0xd9, 0xb4, 0x75,
	0x81, 0x38, 0xee, 0xd9, 0xd0, 0xe9, 0xdb, 0xd3, 0x91, 0xe9, 0x58, 0x7a, 0x83, 0xfc, 0x0a, 0xbe,
	0xa2, 0xc3, 0x89, 0x5c, 0x14, 0xee, 0xd0, 0xb2, 0x4b, 0x2b, 0x60, 0x65, 0x68, 0x8b, 0x3c, 0x83,
	0x27, 0xa7, 0xce, 0x9b, 0x13, 0xcf, 0x15, 0x6a, 0x63, 0x9b, 0x9e, 0x09, 0x03, 0xd6, 0xf0, 0xdc,
	0xd5, 0xb7, 0x49, 0x0f, 0x3e, 0x1f, 0x4c, 0x5c, 0x6b, 0x6a, 0x5a, 0x16, 0xb5, 0xc7, 0xe3, 0x69,
	0x9f, 0xda, 0xa6, 0x67, 0x5b, 0x7a, 0x53, 0xec, 0xa0, 0x8a, 0x64, 0xe2, 0x8e, 0x47, 0x76, 0xc9,
	0xc1, 0x1d, 0x42, 0xa0, 0x7b, 0x6c, 0xf6, 0x7f, 0x98, 0x8c, 0xa6, 0xe3, 0x49, 0x5f, 0x6c, 0x1a,
	0xbd, 0x45, 0xf6, 0xa1, 0xa3, 0x30, 0xf5, 0x38, 0x20, 0x4f, 0x80, 0x28, 0xc8, 0x9c, 0x78, 0x27,
	0x05, 0xde, 0x16, 0x57, 0x2b, 0xbc, 0x70, 0x7d, 0x70, 0xea, 0xf4, 0x3d, 0x7d, 0xb7, 0x64, 0x98,
	0xda, 0x7f, 0x9e, 0xd8, 0x63, 0x4f, 0xef, 0x18, 0xff, 0xd6, 0x40, 0x37, 0x7d, 0x7f, 0xb0, 0x88,
	0x7c, 0x27, 0x0a, 0x38, 0xc5, 0x64, 0xbe, 0xfc, 0xc8, 0x04, 0xf8, 0x16, 0xf6, 0xd7, 0x8c, 0xc0,
	0xc2, 0x24, 0xce, 0x82, 0xa2, 0x8f, 0xee, 0x0a, 0xc4, 0xa4, 0x42, 0x31, 0x8e, 0xde, 0xe6, 0x6c,
	0x4c, 0x75, 0x55, 0x05, 0x13, 0x3b, 0xe7, 0x82, 0xcd, 0xde, 0x2d, 0x92, 0x3f, 0x65, 0x71, 0xa4,
	0xba, 0xaa, 0x84, 0x88, 0x76, 0x48, 0xf1, 0xfd, 0x22, 0x48, 0xd1, 0x2f, 0x38, 0x40, 0x4e, 0x64,
	0x36, 0x61, 0xe3, 0x08, 0x76, 0xd5, 0x4b, 0xf2, 0x57, 0x6c, 0xde, 0xae, 0xdd, 0xbd, 0xdd, 0x18,
	0x42, 0x87, 0xe2, 0xa5, 0xfc, 0xe4, 0xff, 0x0d, 0xbf, 0xaf, 0xa1, 0x93, 0x4a, 0x55, 0x53, 0xc9,
	0xf3, 0x81, 0x54, 0x05, 0x8d, 0x7f, 0x68, 0x2b, 0x2f, 0xf2, 0x49, 0xfc, 0x09, 0x5e, 0x90, 0x57,
	0x40, 0xc4, 0x07, 0x99, 0x7d, 0x3b, 0x43, 0xf4, 0xd1, 0x3f, 0x0d, 0x42, 0x15, 0xd6, 0x1d, 0x7a,
	0x8f, 0x44, 0xc4, 0xac, 0x44, 0x5c, 0xeb, 0x72, 0x6d, 0x42, 0x95, 0xb7, 0x5e, 0xc7, 0x8b, 0x34,
	0xf3, 0xe2, 0x49, 0x24, 0x60, 0x19, 0xd6, 0x1a, 0xad, 0x82, 0xc6, 0x7f, 0x34, 0xd8, 0x13, 0xc6,
	0x15, 0x7b, 0x94, 0x31, 0xfb, 0x7e, 0xc5, 0x37, 0xf3, 0x06, 0x3e, 0xc8, 0x1b, 0x78, 0x43, 0xad,
	0x7c, 0x2e, 0x48, 0xe7, 0x21, 0x6c, 0xc9, 0x37, 0x49, 0xb7, 0xdb, 0x47, 0x44, 0x11, 0xd5, 0x52,
	0x28, 0x68, 0xae, 0x60, 0x9c, 0x01, 0xac, 0xbf, 0x17, 0x8b, 0xd5, 0x1d, 0x4e, 0x45, 0x4b, 0xe8,
	0x8f, 0x44, 0xed, 0x16, 0x04, 0x6d, 0x83, 0x98, 0x75, 0xa0, 0xa5, 0x10, 0xd9, 0xc4, 0x04, 0xba,
	0x1e, 0x35, 0xdd, 0xf1, 0xc0, 0xa6, 0x53, 0x9b, 0xd2, 0x21, 0xd5, 0xeb, 0x86, 0x0d, 0xfb, 0x14,
	0xc3, 0xf8, 0x06, 0x07, 0x9f, 0x94, 0xcf, 0x07, 0xf6, 0x80, 0xe1, 0xc0, 0x5e, 0xd9, 0x8c, 0x88,
	0x0a, 0x81, 0x06, 0xbf, 0x5d, 0xf1, 0x7a, 0xf9, 0xfb, 0x4e, 0x5e, 0x6b, 0xf7, 0x54, 0xd7, 0x3f,
	0x6b, 0xb0, 0x37, 0xfe, 0xc0, 0x12, 0x55, 0x1c, 0x4e, 0x74, 0x19, 0x7f, 0xc4, 0xa1, 0x83, 0x15,
	0xe3, 0x90, 0xec, 0x4a, 0xed, 0xec, 0x12, 0x24, 0x7a, 0xa1, 0x1f, 0x47, 0x97, 0x41, 0x1a, 0xa2,
	0x6f, 0x96, 0x39, 0xe2, 0x26, 0x2c, 0x58, 0xd6, 0x0a, 0xf2, 0xc4, 0xda, 0x60, 0x33, 0x31, 0x3b,
	0x1d, 0x5f, 0xfc, 0x43, 0x42, 0xcc, 0xd6, 0x87, 0xc4, 0xa2, 0xb6, 0xc4, 0x78, 0x57, 0xe6, 0xf3,
	0x56, 0x2b, 0x21, 0x1b, 0xb5, 0xb7, 0x7d, 0xa7, 0xf6, 0x36, 0xe3, 0xd2, 0xbc, 0xa7, 0xde, 0x5f,
	0x42, 0x77, 0xce, 0x32, 0x9e, 0x77, 0x9e, 0xe4, 0x9a, 0x39, 0x95, 0xdc, 0x40, 0x8d, 0x41, 0x25,
	0x7c, 0x92, 0x42, 0xbd, 0x86, 0x96, 0x8a, 0x17, 0x66, 0x8a, 0x3f, 0x3d, 0xce, 0x4b, 0x6d, 0x23,
	0xd0, 0x74, 0xad, 0x67, 0xfc, 0x5d, 0x83, 0xe7, 0x7d, 0x41, 0x91, 0x91, 0x32, 0x3e, 0xbb, 0x46,
	0x3e, 0xc6, 0x2c, 0x0b, 0xe2, 0xa8, 0xb4, 0x48, 0x33, 0x9c, 0xa5, 0xc8, 0x55, 0x4a, 0xd4, 0x49,
	0xbc, 0x25, 0xc5, 0x30, 0xe6, 0x38, 0x5a, 0x5c, 0xfc, 0x80, 0xcb, 0x22, 0xc7, 0x65, 0x4c, 0xac,
	0xfc, 0x2c, 0xb7, 0xe6, 0x58, 0x05, 0x6d, 0x58, 0x01, 0xa5, 0x15, 0x2d, 0x5a, 0xb0, 0xb1, 0x5a,
	0xd1, 0x01, 0x3c, 0xbd, 0xdf, 0x21, 0x51, 0x6e, 0x15, 0x93, 0xda, 0x3d, 0x26, 0x95, 0xb3, 0xb5,
	0x8a, 0xb3, 0x4f, 0x60, 0x3b, 0xc9, 0xdd, 0xcc, 0xbd, 0x50, 0x27, 0xe3, 0x3d, 0x7c, 0x51, 0xbd,
	0x44, 0x46, 0xe7, 0x13, 0x2e, 0x7a, 0x01, 0xad, 0x20, 0x0a, 0x78, 0xc0, 0xf8, 0x8a, 0x16, 0xac,
	0x01, 0xc1, 0x9d, 0x17, 0x19, 0xa6, 0xc2, 0x98, 0xba, 0x70, 0x75, 0x36, 0xfe, 0x02, 0x2f, 0xaa,
	0x57, 0x8e, 0x91, 0xe7, 0xb7, 0xe6, 0xf1, 0xfe, 0xf8, 0xbd, 0x65, 0xcb, 0xb5, 0x0d, 0xcb, 0x43,
	0x78, 0xac, 0x2c, 0xdb, 0xd1, 0x2c, 0x5d, 0x26, 0xfc, 0xd3, 0x4c, 0xf6, 0xa0, 0x19, 0x56, 0xfa,
	0xb4, 0x38, 0x1a, 0x6c, 0x65, 0xd0, 0xc2, 0x5f, 0x60, 0xf0, 0x1b, 0xd0, 0x31, 0x77, 0x00, 0xfd,
	0xea, 0x04, 0xb8, 0x83, 0x1b, 0x13, 0x78, 0x7c, 0x1c, 0xc7, 0x3c, 0xe3, 0x29, 0x4b, 0x06, 0xc1,
	0x1c, 0x57, 0x44, 0xfb, 0x4b, 0x80, 0xf3, 0x38, 0x7d, 0x17, 0x44, 0x57, 0x56, 0x50, 0xd0, 0xf8,
	0x12, 0x22, 0x5c, 0x18, 0x2c, 0xe6, 0xf3, 0x11, 0xe3, 0xd7, 0x99, 0xa2, 0x44, 0x6b, 0xc0, 0xf8,
	0x3d, 0x6c, 0x8d, 0x10, 0xd3, 0x4c, 0xe6, 0x29, 0xb3, 0xf0, 0x92, 0x2d, 0xe6, 0x79, 0x01, 0x8b,
	0x3c, 0x15, 0x80, 0x98, 0x5d, 0x09, 0x62, 0x5a, 0x50, 0x2a, 0xf1, 0xdb, 0xf8, 0x0e, 0x1a, 0x29,
	0xe3, 0x92, 0x6e, 0xcd, 0xe2, 0xa0, 0x60, 0xc9, 0xf2, 0x37, 0xf9, 0x1c, 0xb6, 0x6e, 0xd8, 0x7c,
	0x91, 0x3f, 0x47, 0xa3, 0xf9, 0xc1, 0xf8, 0x0d, 0x6c, 0x51, 0xc6, 0x51, 0x0c, 0xa9, 0x2d, 0xf1,
	0x69, 0xd1, 0x7b, 0x90, 0xf7, 0x9e, 0x80, 0x68, 0x2e, 0xb8, 0xd8, 0x96, 0xff, 0xe5, 0xf2, 0xfa,
	0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x29, 0xf6, 0x3c, 0xb5, 0x84, 0x11, 0x00, 0x00,
}
