// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

/*
Package data is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	ChainStatus
	Account
	Payment
	PaymentsList
	SendNonDepositedCoinsRequest
	PayInvoiceRequest
	InvoiceMemo
	Invoice
	NotificationEvent
	AddFundInitReply
	AddFundReply
	RefundRequest
	FundStatusReply
	RemoveFundRequest
	RemoveFundReply
	SwapAddressInfo
	SwapAddressList
	CreateRatchetSessionRequest
	CreateRatchetSessionReply
	RatchetSessionInfoReply
	RatchetSessionSetInfoRequest
	RatchetEncryptRequest
	RatchetDecryptRequest
	BootstrapFilesRequest
*/
package data

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Account_AccountStatus int32

const (
	Account_WAITING_DEPOSIT              Account_AccountStatus = 0
	Account_WAITING_DEPOSIT_CONFIRMATION Account_AccountStatus = 1
	Account_PROCESSING_BREEZ_CONNECTION  Account_AccountStatus = 2
	Account_PROCESSING_WITHDRAWAL        Account_AccountStatus = 3
	Account_ACTIVE                       Account_AccountStatus = 4
)

var Account_AccountStatus_name = map[int32]string{
	0: "WAITING_DEPOSIT",
	1: "WAITING_DEPOSIT_CONFIRMATION",
	2: "PROCESSING_BREEZ_CONNECTION",
	3: "PROCESSING_WITHDRAWAL",
	4: "ACTIVE",
}
var Account_AccountStatus_value = map[string]int32{
	"WAITING_DEPOSIT":              0,
	"WAITING_DEPOSIT_CONFIRMATION": 1,
	"PROCESSING_BREEZ_CONNECTION":  2,
	"PROCESSING_WITHDRAWAL":        3,
	"ACTIVE":                       4,
}

func (x Account_AccountStatus) String() string {
	return proto.EnumName(Account_AccountStatus_name, int32(x))
}
func (Account_AccountStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Payment_PaymentType int32

const (
	Payment_DEPOSIT    Payment_PaymentType = 0
	Payment_WITHDRAWAL Payment_PaymentType = 1
	Payment_SENT       Payment_PaymentType = 2
	Payment_RECEIVED   Payment_PaymentType = 3
)

var Payment_PaymentType_name = map[int32]string{
	0: "DEPOSIT",
	1: "WITHDRAWAL",
	2: "SENT",
	3: "RECEIVED",
}
var Payment_PaymentType_value = map[string]int32{
	"DEPOSIT":    0,
	"WITHDRAWAL": 1,
	"SENT":       2,
	"RECEIVED":   3,
}

func (x Payment_PaymentType) String() string {
	return proto.EnumName(Payment_PaymentType_name, int32(x))
}
func (Payment_PaymentType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type NotificationEvent_NotificationType int32

const (
	NotificationEvent_READY                           NotificationEvent_NotificationType = 0
	NotificationEvent_INITIALIZATION_FAILED           NotificationEvent_NotificationType = 1
	NotificationEvent_ACCOUNT_CHANGED                 NotificationEvent_NotificationType = 2
	NotificationEvent_INVOICE_PAID                    NotificationEvent_NotificationType = 3
	NotificationEvent_ROUTING_NODE_CONNECTION_CHANGED NotificationEvent_NotificationType = 4
	NotificationEvent_LIGHTNING_SERVICE_DOWN          NotificationEvent_NotificationType = 5
	NotificationEvent_FUND_ADDRESS_UNSPENT_CHANGED    NotificationEvent_NotificationType = 6
	NotificationEvent_BACKUP_FILES_AVAILABLE          NotificationEvent_NotificationType = 7
)

var NotificationEvent_NotificationType_name = map[int32]string{
	0: "READY",
	1: "INITIALIZATION_FAILED",
	2: "ACCOUNT_CHANGED",
	3: "INVOICE_PAID",
	4: "ROUTING_NODE_CONNECTION_CHANGED",
	5: "LIGHTNING_SERVICE_DOWN",
	6: "FUND_ADDRESS_UNSPENT_CHANGED",
	7: "BACKUP_FILES_AVAILABLE",
}
var NotificationEvent_NotificationType_value = map[string]int32{
	"READY":                           0,
	"INITIALIZATION_FAILED":           1,
	"ACCOUNT_CHANGED":                 2,
	"INVOICE_PAID":                    3,
	"ROUTING_NODE_CONNECTION_CHANGED": 4,
	"LIGHTNING_SERVICE_DOWN":          5,
	"FUND_ADDRESS_UNSPENT_CHANGED":    6,
	"BACKUP_FILES_AVAILABLE":          7,
}

func (x NotificationEvent_NotificationType) String() string {
	return proto.EnumName(NotificationEvent_NotificationType_name, int32(x))
}
func (NotificationEvent_NotificationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8, 0}
}

type FundStatusReply_FundStatus int32

const (
	FundStatusReply_NO_FUND              FundStatusReply_FundStatus = 0
	FundStatusReply_WAITING_CONFIRMATION FundStatusReply_FundStatus = 1
	FundStatusReply_CONFIRMED            FundStatusReply_FundStatus = 2
)

var FundStatusReply_FundStatus_name = map[int32]string{
	0: "NO_FUND",
	1: "WAITING_CONFIRMATION",
	2: "CONFIRMED",
}
var FundStatusReply_FundStatus_value = map[string]int32{
	"NO_FUND":              0,
	"WAITING_CONFIRMATION": 1,
	"CONFIRMED":            2,
}

func (x FundStatusReply_FundStatus) String() string {
	return proto.EnumName(FundStatusReply_FundStatus_name, int32(x))
}
func (FundStatusReply_FundStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{12, 0}
}

type ChainStatus struct {
	BlockHeight   uint32 `protobuf:"varint,1,opt,name=blockHeight" json:"blockHeight,omitempty"`
	SyncedToChain bool   `protobuf:"varint,2,opt,name=syncedToChain" json:"syncedToChain,omitempty"`
}

func (m *ChainStatus) Reset()                    { *m = ChainStatus{} }
func (m *ChainStatus) String() string            { return proto.CompactTextString(m) }
func (*ChainStatus) ProtoMessage()               {}
func (*ChainStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ChainStatus) GetBlockHeight() uint32 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *ChainStatus) GetSyncedToChain() bool {
	if m != nil {
		return m.SyncedToChain
	}
	return false
}

type Account struct {
	Id                    string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Balance               int64                 `protobuf:"varint,2,opt,name=balance" json:"balance,omitempty"`
	NonDepositableBalance int64                 `protobuf:"varint,3,opt,name=nonDepositableBalance" json:"nonDepositableBalance,omitempty"`
	Status                Account_AccountStatus `protobuf:"varint,4,opt,name=status,enum=data.Account_AccountStatus" json:"status,omitempty"`
	// maximum payment this node can receive via lightning
	MaxAllowedToReceive int64 `protobuf:"varint,5,opt,name=maxAllowedToReceive" json:"maxAllowedToReceive,omitempty"`
	// maximum payment this node can pay via lightning
	MaxAllowedToPay int64 `protobuf:"varint,6,opt,name=maxAllowedToPay" json:"maxAllowedToPay,omitempty"`
	// The lightning absolute payment amount
	MaxPaymentAmount int64 `protobuf:"varint,7,opt,name=maxPaymentAmount" json:"maxPaymentAmount,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Account) GetNonDepositableBalance() int64 {
	if m != nil {
		return m.NonDepositableBalance
	}
	return 0
}

func (m *Account) GetStatus() Account_AccountStatus {
	if m != nil {
		return m.Status
	}
	return Account_WAITING_DEPOSIT
}

func (m *Account) GetMaxAllowedToReceive() int64 {
	if m != nil {
		return m.MaxAllowedToReceive
	}
	return 0
}

func (m *Account) GetMaxAllowedToPay() int64 {
	if m != nil {
		return m.MaxAllowedToPay
	}
	return 0
}

func (m *Account) GetMaxPaymentAmount() int64 {
	if m != nil {
		return m.MaxPaymentAmount
	}
	return 0
}

type Payment struct {
	Type              Payment_PaymentType `protobuf:"varint,1,opt,name=type,enum=data.Payment_PaymentType" json:"type,omitempty"`
	Amount            int64               `protobuf:"varint,3,opt,name=amount" json:"amount,omitempty"`
	CreationTimestamp int64               `protobuf:"varint,4,opt,name=creationTimestamp" json:"creationTimestamp,omitempty"`
	InvoiceMemo       *InvoiceMemo        `protobuf:"bytes,6,opt,name=invoiceMemo" json:"invoiceMemo,omitempty"`
	RedeemTxID        string              `protobuf:"bytes,7,opt,name=redeemTxID" json:"redeemTxID,omitempty"`
	PaymentHash       string              `protobuf:"bytes,8,opt,name=paymentHash" json:"paymentHash,omitempty"`
	Destination       string              `protobuf:"bytes,9,opt,name=destination" json:"destination,omitempty"`
}

func (m *Payment) Reset()                    { *m = Payment{} }
func (m *Payment) String() string            { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()               {}
func (*Payment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Payment) GetType() Payment_PaymentType {
	if m != nil {
		return m.Type
	}
	return Payment_DEPOSIT
}

func (m *Payment) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Payment) GetCreationTimestamp() int64 {
	if m != nil {
		return m.CreationTimestamp
	}
	return 0
}

func (m *Payment) GetInvoiceMemo() *InvoiceMemo {
	if m != nil {
		return m.InvoiceMemo
	}
	return nil
}

func (m *Payment) GetRedeemTxID() string {
	if m != nil {
		return m.RedeemTxID
	}
	return ""
}

func (m *Payment) GetPaymentHash() string {
	if m != nil {
		return m.PaymentHash
	}
	return ""
}

func (m *Payment) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type PaymentsList struct {
	PaymentsList []*Payment `protobuf:"bytes,1,rep,name=paymentsList" json:"paymentsList,omitempty"`
}

func (m *PaymentsList) Reset()                    { *m = PaymentsList{} }
func (m *PaymentsList) String() string            { return proto.CompactTextString(m) }
func (*PaymentsList) ProtoMessage()               {}
func (*PaymentsList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PaymentsList) GetPaymentsList() []*Payment {
	if m != nil {
		return m.PaymentsList
	}
	return nil
}

type SendNonDepositedCoinsRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
}

func (m *SendNonDepositedCoinsRequest) Reset()                    { *m = SendNonDepositedCoinsRequest{} }
func (m *SendNonDepositedCoinsRequest) String() string            { return proto.CompactTextString(m) }
func (*SendNonDepositedCoinsRequest) ProtoMessage()               {}
func (*SendNonDepositedCoinsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SendNonDepositedCoinsRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type PayInvoiceRequest struct {
	Amount         int64  `protobuf:"varint,1,opt,name=amount" json:"amount,omitempty"`
	PaymentRequest string `protobuf:"bytes,2,opt,name=paymentRequest" json:"paymentRequest,omitempty"`
}

func (m *PayInvoiceRequest) Reset()                    { *m = PayInvoiceRequest{} }
func (m *PayInvoiceRequest) String() string            { return proto.CompactTextString(m) }
func (*PayInvoiceRequest) ProtoMessage()               {}
func (*PayInvoiceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PayInvoiceRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *PayInvoiceRequest) GetPaymentRequest() string {
	if m != nil {
		return m.PaymentRequest
	}
	return ""
}

type InvoiceMemo struct {
	Description     string `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
	Amount          int64  `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
	PayeeName       string `protobuf:"bytes,3,opt,name=payeeName" json:"payeeName,omitempty"`
	PayeeImageURL   string `protobuf:"bytes,4,opt,name=payeeImageURL" json:"payeeImageURL,omitempty"`
	PayerName       string `protobuf:"bytes,5,opt,name=payerName" json:"payerName,omitempty"`
	PayerImageURL   string `protobuf:"bytes,6,opt,name=payerImageURL" json:"payerImageURL,omitempty"`
	TransferRequest bool   `protobuf:"varint,7,opt,name=transferRequest" json:"transferRequest,omitempty"`
	Expiry          int64  `protobuf:"varint,8,opt,name=expiry" json:"expiry,omitempty"`
}

func (m *InvoiceMemo) Reset()                    { *m = InvoiceMemo{} }
func (m *InvoiceMemo) String() string            { return proto.CompactTextString(m) }
func (*InvoiceMemo) ProtoMessage()               {}
func (*InvoiceMemo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *InvoiceMemo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *InvoiceMemo) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *InvoiceMemo) GetPayeeName() string {
	if m != nil {
		return m.PayeeName
	}
	return ""
}

func (m *InvoiceMemo) GetPayeeImageURL() string {
	if m != nil {
		return m.PayeeImageURL
	}
	return ""
}

func (m *InvoiceMemo) GetPayerName() string {
	if m != nil {
		return m.PayerName
	}
	return ""
}

func (m *InvoiceMemo) GetPayerImageURL() string {
	if m != nil {
		return m.PayerImageURL
	}
	return ""
}

func (m *InvoiceMemo) GetTransferRequest() bool {
	if m != nil {
		return m.TransferRequest
	}
	return false
}

func (m *InvoiceMemo) GetExpiry() int64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

type Invoice struct {
	Memo    *InvoiceMemo `protobuf:"bytes,1,opt,name=memo" json:"memo,omitempty"`
	Settled bool         `protobuf:"varint,2,opt,name=settled" json:"settled,omitempty"`
	AmtPaid int64        `protobuf:"varint,3,opt,name=amtPaid" json:"amtPaid,omitempty"`
}

func (m *Invoice) Reset()                    { *m = Invoice{} }
func (m *Invoice) String() string            { return proto.CompactTextString(m) }
func (*Invoice) ProtoMessage()               {}
func (*Invoice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Invoice) GetMemo() *InvoiceMemo {
	if m != nil {
		return m.Memo
	}
	return nil
}

func (m *Invoice) GetSettled() bool {
	if m != nil {
		return m.Settled
	}
	return false
}

func (m *Invoice) GetAmtPaid() int64 {
	if m != nil {
		return m.AmtPaid
	}
	return 0
}

type NotificationEvent struct {
	Type NotificationEvent_NotificationType `protobuf:"varint,1,opt,name=type,enum=data.NotificationEvent_NotificationType" json:"type,omitempty"`
	Data []string                           `protobuf:"bytes,2,rep,name=data" json:"data,omitempty"`
}

func (m *NotificationEvent) Reset()                    { *m = NotificationEvent{} }
func (m *NotificationEvent) String() string            { return proto.CompactTextString(m) }
func (*NotificationEvent) ProtoMessage()               {}
func (*NotificationEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *NotificationEvent) GetType() NotificationEvent_NotificationType {
	if m != nil {
		return m.Type
	}
	return NotificationEvent_READY
}

func (m *NotificationEvent) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

type AddFundInitReply struct {
	Address           string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	MaxAllowedDeposit int64  `protobuf:"varint,2,opt,name=maxAllowedDeposit" json:"maxAllowedDeposit,omitempty"`
	ErrorMessage      string `protobuf:"bytes,3,opt,name=errorMessage" json:"errorMessage,omitempty"`
	BackupJson        string `protobuf:"bytes,4,opt,name=backupJson" json:"backupJson,omitempty"`
}

func (m *AddFundInitReply) Reset()                    { *m = AddFundInitReply{} }
func (m *AddFundInitReply) String() string            { return proto.CompactTextString(m) }
func (*AddFundInitReply) ProtoMessage()               {}
func (*AddFundInitReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *AddFundInitReply) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AddFundInitReply) GetMaxAllowedDeposit() int64 {
	if m != nil {
		return m.MaxAllowedDeposit
	}
	return 0
}

func (m *AddFundInitReply) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *AddFundInitReply) GetBackupJson() string {
	if m != nil {
		return m.BackupJson
	}
	return ""
}

type AddFundReply struct {
	ErrorMessage string `protobuf:"bytes,1,opt,name=errorMessage" json:"errorMessage,omitempty"`
}

func (m *AddFundReply) Reset()                    { *m = AddFundReply{} }
func (m *AddFundReply) String() string            { return proto.CompactTextString(m) }
func (*AddFundReply) ProtoMessage()               {}
func (*AddFundReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *AddFundReply) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type RefundRequest struct {
	Address       string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	RefundAddress string `protobuf:"bytes,2,opt,name=refundAddress" json:"refundAddress,omitempty"`
}

func (m *RefundRequest) Reset()                    { *m = RefundRequest{} }
func (m *RefundRequest) String() string            { return proto.CompactTextString(m) }
func (*RefundRequest) ProtoMessage()               {}
func (*RefundRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *RefundRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RefundRequest) GetRefundAddress() string {
	if m != nil {
		return m.RefundAddress
	}
	return ""
}

type FundStatusReply struct {
	Status FundStatusReply_FundStatus `protobuf:"varint,1,opt,name=status,enum=data.FundStatusReply_FundStatus" json:"status,omitempty"`
}

func (m *FundStatusReply) Reset()                    { *m = FundStatusReply{} }
func (m *FundStatusReply) String() string            { return proto.CompactTextString(m) }
func (*FundStatusReply) ProtoMessage()               {}
func (*FundStatusReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *FundStatusReply) GetStatus() FundStatusReply_FundStatus {
	if m != nil {
		return m.Status
	}
	return FundStatusReply_NO_FUND
}

type RemoveFundRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Amount  int64  `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *RemoveFundRequest) Reset()                    { *m = RemoveFundRequest{} }
func (m *RemoveFundRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveFundRequest) ProtoMessage()               {}
func (*RemoveFundRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *RemoveFundRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RemoveFundRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type RemoveFundReply struct {
	Txid         string `protobuf:"bytes,1,opt,name=txid" json:"txid,omitempty"`
	ErrorMessage string `protobuf:"bytes,2,opt,name=errorMessage" json:"errorMessage,omitempty"`
}

func (m *RemoveFundReply) Reset()                    { *m = RemoveFundReply{} }
func (m *RemoveFundReply) String() string            { return proto.CompactTextString(m) }
func (*RemoveFundReply) ProtoMessage()               {}
func (*RemoveFundReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *RemoveFundReply) GetTxid() string {
	if m != nil {
		return m.Txid
	}
	return ""
}

func (m *RemoveFundReply) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type SwapAddressInfo struct {
	Address                 string   `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	PaymentHash             string   `protobuf:"bytes,2,opt,name=PaymentHash" json:"PaymentHash,omitempty"`
	ConfirmedAmount         int64    `protobuf:"varint,3,opt,name=ConfirmedAmount" json:"ConfirmedAmount,omitempty"`
	ConfirmedTransactionIds []string `protobuf:"bytes,4,rep,name=ConfirmedTransactionIds" json:"ConfirmedTransactionIds,omitempty"`
	PaidAmount              int64    `protobuf:"varint,5,opt,name=PaidAmount" json:"PaidAmount,omitempty"`
	LockHeight              uint32   `protobuf:"varint,6,opt,name=lockHeight" json:"lockHeight,omitempty"`
	ErrorMessage            string   `protobuf:"bytes,7,opt,name=errorMessage" json:"errorMessage,omitempty"`
	LastRefundTxID          string   `protobuf:"bytes,8,opt,name=lastRefundTxID" json:"lastRefundTxID,omitempty"`
}

func (m *SwapAddressInfo) Reset()                    { *m = SwapAddressInfo{} }
func (m *SwapAddressInfo) String() string            { return proto.CompactTextString(m) }
func (*SwapAddressInfo) ProtoMessage()               {}
func (*SwapAddressInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *SwapAddressInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SwapAddressInfo) GetPaymentHash() string {
	if m != nil {
		return m.PaymentHash
	}
	return ""
}

func (m *SwapAddressInfo) GetConfirmedAmount() int64 {
	if m != nil {
		return m.ConfirmedAmount
	}
	return 0
}

func (m *SwapAddressInfo) GetConfirmedTransactionIds() []string {
	if m != nil {
		return m.ConfirmedTransactionIds
	}
	return nil
}

func (m *SwapAddressInfo) GetPaidAmount() int64 {
	if m != nil {
		return m.PaidAmount
	}
	return 0
}

func (m *SwapAddressInfo) GetLockHeight() uint32 {
	if m != nil {
		return m.LockHeight
	}
	return 0
}

func (m *SwapAddressInfo) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *SwapAddressInfo) GetLastRefundTxID() string {
	if m != nil {
		return m.LastRefundTxID
	}
	return ""
}

type SwapAddressList struct {
	Addresses []*SwapAddressInfo `protobuf:"bytes,1,rep,name=addresses" json:"addresses,omitempty"`
}

func (m *SwapAddressList) Reset()                    { *m = SwapAddressList{} }
func (m *SwapAddressList) String() string            { return proto.CompactTextString(m) }
func (*SwapAddressList) ProtoMessage()               {}
func (*SwapAddressList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *SwapAddressList) GetAddresses() []*SwapAddressInfo {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type CreateRatchetSessionRequest struct {
	Secret       string `protobuf:"bytes,1,opt,name=secret" json:"secret,omitempty"`
	RemotePubKey string `protobuf:"bytes,2,opt,name=remotePubKey" json:"remotePubKey,omitempty"`
	SessionID    string `protobuf:"bytes,3,opt,name=sessionID" json:"sessionID,omitempty"`
	Expiry       uint64 `protobuf:"varint,4,opt,name=expiry" json:"expiry,omitempty"`
}

func (m *CreateRatchetSessionRequest) Reset()                    { *m = CreateRatchetSessionRequest{} }
func (m *CreateRatchetSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRatchetSessionRequest) ProtoMessage()               {}
func (*CreateRatchetSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *CreateRatchetSessionRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *CreateRatchetSessionRequest) GetRemotePubKey() string {
	if m != nil {
		return m.RemotePubKey
	}
	return ""
}

func (m *CreateRatchetSessionRequest) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *CreateRatchetSessionRequest) GetExpiry() uint64 {
	if m != nil {
		return m.Expiry
	}
	return 0
}

type CreateRatchetSessionReply struct {
	SessionID string `protobuf:"bytes,1,opt,name=sessionID" json:"sessionID,omitempty"`
	Secret    string `protobuf:"bytes,2,opt,name=secret" json:"secret,omitempty"`
	PubKey    string `protobuf:"bytes,3,opt,name=pubKey" json:"pubKey,omitempty"`
}

func (m *CreateRatchetSessionReply) Reset()                    { *m = CreateRatchetSessionReply{} }
func (m *CreateRatchetSessionReply) String() string            { return proto.CompactTextString(m) }
func (*CreateRatchetSessionReply) ProtoMessage()               {}
func (*CreateRatchetSessionReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *CreateRatchetSessionReply) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *CreateRatchetSessionReply) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

func (m *CreateRatchetSessionReply) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

type RatchetSessionInfoReply struct {
	SessionID string `protobuf:"bytes,1,opt,name=sessionID" json:"sessionID,omitempty"`
	Initiated bool   `protobuf:"varint,2,opt,name=initiated" json:"initiated,omitempty"`
	UserInfo  string `protobuf:"bytes,3,opt,name=userInfo" json:"userInfo,omitempty"`
}

func (m *RatchetSessionInfoReply) Reset()                    { *m = RatchetSessionInfoReply{} }
func (m *RatchetSessionInfoReply) String() string            { return proto.CompactTextString(m) }
func (*RatchetSessionInfoReply) ProtoMessage()               {}
func (*RatchetSessionInfoReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *RatchetSessionInfoReply) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *RatchetSessionInfoReply) GetInitiated() bool {
	if m != nil {
		return m.Initiated
	}
	return false
}

func (m *RatchetSessionInfoReply) GetUserInfo() string {
	if m != nil {
		return m.UserInfo
	}
	return ""
}

type RatchetSessionSetInfoRequest struct {
	SessionID string `protobuf:"bytes,1,opt,name=sessionID" json:"sessionID,omitempty"`
	UserInfo  string `protobuf:"bytes,2,opt,name=userInfo" json:"userInfo,omitempty"`
}

func (m *RatchetSessionSetInfoRequest) Reset()                    { *m = RatchetSessionSetInfoRequest{} }
func (m *RatchetSessionSetInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*RatchetSessionSetInfoRequest) ProtoMessage()               {}
func (*RatchetSessionSetInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *RatchetSessionSetInfoRequest) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *RatchetSessionSetInfoRequest) GetUserInfo() string {
	if m != nil {
		return m.UserInfo
	}
	return ""
}

type RatchetEncryptRequest struct {
	SessionID string `protobuf:"bytes,1,opt,name=sessionID" json:"sessionID,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *RatchetEncryptRequest) Reset()                    { *m = RatchetEncryptRequest{} }
func (m *RatchetEncryptRequest) String() string            { return proto.CompactTextString(m) }
func (*RatchetEncryptRequest) ProtoMessage()               {}
func (*RatchetEncryptRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *RatchetEncryptRequest) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *RatchetEncryptRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RatchetDecryptRequest struct {
	SessionID        string `protobuf:"bytes,1,opt,name=sessionID" json:"sessionID,omitempty"`
	EncryptedMessage string `protobuf:"bytes,2,opt,name=encryptedMessage" json:"encryptedMessage,omitempty"`
}

func (m *RatchetDecryptRequest) Reset()                    { *m = RatchetDecryptRequest{} }
func (m *RatchetDecryptRequest) String() string            { return proto.CompactTextString(m) }
func (*RatchetDecryptRequest) ProtoMessage()               {}
func (*RatchetDecryptRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *RatchetDecryptRequest) GetSessionID() string {
	if m != nil {
		return m.SessionID
	}
	return ""
}

func (m *RatchetDecryptRequest) GetEncryptedMessage() string {
	if m != nil {
		return m.EncryptedMessage
	}
	return ""
}

type BootstrapFilesRequest struct {
	WorkingDir string   `protobuf:"bytes,1,opt,name=WorkingDir" json:"WorkingDir,omitempty"`
	FullPaths  []string `protobuf:"bytes,2,rep,name=FullPaths" json:"FullPaths,omitempty"`
}

func (m *BootstrapFilesRequest) Reset()                    { *m = BootstrapFilesRequest{} }
func (m *BootstrapFilesRequest) String() string            { return proto.CompactTextString(m) }
func (*BootstrapFilesRequest) ProtoMessage()               {}
func (*BootstrapFilesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *BootstrapFilesRequest) GetWorkingDir() string {
	if m != nil {
		return m.WorkingDir
	}
	return ""
}

func (m *BootstrapFilesRequest) GetFullPaths() []string {
	if m != nil {
		return m.FullPaths
	}
	return nil
}

func init() {
	proto.RegisterType((*ChainStatus)(nil), "data.ChainStatus")
	proto.RegisterType((*Account)(nil), "data.Account")
	proto.RegisterType((*Payment)(nil), "data.Payment")
	proto.RegisterType((*PaymentsList)(nil), "data.PaymentsList")
	proto.RegisterType((*SendNonDepositedCoinsRequest)(nil), "data.SendNonDepositedCoinsRequest")
	proto.RegisterType((*PayInvoiceRequest)(nil), "data.PayInvoiceRequest")
	proto.RegisterType((*InvoiceMemo)(nil), "data.InvoiceMemo")
	proto.RegisterType((*Invoice)(nil), "data.Invoice")
	proto.RegisterType((*NotificationEvent)(nil), "data.NotificationEvent")
	proto.RegisterType((*AddFundInitReply)(nil), "data.AddFundInitReply")
	proto.RegisterType((*AddFundReply)(nil), "data.AddFundReply")
	proto.RegisterType((*RefundRequest)(nil), "data.RefundRequest")
	proto.RegisterType((*FundStatusReply)(nil), "data.FundStatusReply")
	proto.RegisterType((*RemoveFundRequest)(nil), "data.RemoveFundRequest")
	proto.RegisterType((*RemoveFundReply)(nil), "data.RemoveFundReply")
	proto.RegisterType((*SwapAddressInfo)(nil), "data.SwapAddressInfo")
	proto.RegisterType((*SwapAddressList)(nil), "data.SwapAddressList")
	proto.RegisterType((*CreateRatchetSessionRequest)(nil), "data.CreateRatchetSessionRequest")
	proto.RegisterType((*CreateRatchetSessionReply)(nil), "data.CreateRatchetSessionReply")
	proto.RegisterType((*RatchetSessionInfoReply)(nil), "data.RatchetSessionInfoReply")
	proto.RegisterType((*RatchetSessionSetInfoRequest)(nil), "data.RatchetSessionSetInfoRequest")
	proto.RegisterType((*RatchetEncryptRequest)(nil), "data.RatchetEncryptRequest")
	proto.RegisterType((*RatchetDecryptRequest)(nil), "data.RatchetDecryptRequest")
	proto.RegisterType((*BootstrapFilesRequest)(nil), "data.BootstrapFilesRequest")
	proto.RegisterEnum("data.Account_AccountStatus", Account_AccountStatus_name, Account_AccountStatus_value)
	proto.RegisterEnum("data.Payment_PaymentType", Payment_PaymentType_name, Payment_PaymentType_value)
	proto.RegisterEnum("data.NotificationEvent_NotificationType", NotificationEvent_NotificationType_name, NotificationEvent_NotificationType_value)
	proto.RegisterEnum("data.FundStatusReply_FundStatus", FundStatusReply_FundStatus_name, FundStatusReply_FundStatus_value)
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1471 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0xdd, 0x6e, 0xdb, 0x46,
	0x16, 0x0e, 0x25, 0x59, 0xb2, 0x8e, 0xfc, 0x43, 0x4f, 0xd6, 0x89, 0x92, 0x18, 0x89, 0xc0, 0xdd,
	0x0d, 0x8c, 0x60, 0x37, 0xd8, 0xb5, 0xf7, 0x22, 0x17, 0x7b, 0x43, 0x8b, 0x54, 0xcc, 0x46, 0xa1,
	0x84, 0xa1, 0x64, 0xb7, 0xb9, 0x11, 0xc6, 0xe4, 0xd8, 0x26, 0x22, 0xfe, 0x84, 0x1c, 0x39, 0xd6,
	0x4b, 0xb4, 0xe8, 0x0b, 0xf4, 0x35, 0x7a, 0xd5, 0xdb, 0xbe, 0x44, 0x81, 0x3e, 0x4b, 0x31, 0xc3,
	0x11, 0x45, 0x4a, 0x76, 0x9a, 0x5e, 0xc9, 0xe7, 0x9b, 0xc3, 0xef, 0x9c, 0x39, 0xbf, 0x63, 0xd8,
	0x09, 0x68, 0x9a, 0x92, 0x2b, 0x9a, 0xbe, 0x8e, 0x93, 0x88, 0x45, 0xa8, 0xe6, 0x11, 0x46, 0xb4,
	0x31, 0xb4, 0xba, 0xd7, 0xc4, 0x0f, 0x1d, 0x46, 0xd8, 0x2c, 0x45, 0x1d, 0x68, 0x5d, 0x4c, 0x23,
	0xf7, 0xe3, 0x29, 0xf5, 0xaf, 0xae, 0x59, 0x5b, 0xe9, 0x28, 0x87, 0xdb, 0xb8, 0x08, 0xa1, 0x7f,
	0xc0, 0x76, 0x3a, 0x0f, 0x5d, 0xea, 0x8d, 0x22, 0xf1, 0x61, 0xbb, 0xd2, 0x51, 0x0e, 0x37, 0x71,
	0x19, 0xd4, 0x7e, 0xae, 0x42, 0x43, 0x77, 0xdd, 0x68, 0x16, 0x32, 0xb4, 0x03, 0x15, 0xdf, 0x13,
	0x54, 0x4d, 0x5c, 0xf1, 0x3d, 0xd4, 0x86, 0xc6, 0x05, 0x99, 0x92, 0xd0, 0xa5, 0xe2, 0xdb, 0x2a,
	0x5e, 0x88, 0xe8, 0x7f, 0xb0, 0x1f, 0x46, 0xa1, 0x41, 0xe3, 0x28, 0xf5, 0x19, 0xb9, 0x98, 0xd2,
	0x13, 0xa9, 0x57, 0x15, 0x7a, 0x77, 0x1f, 0xa2, 0x63, 0xa8, 0xa7, 0xc2, 0xfb, 0x76, 0xad, 0xa3,
	0x1c, 0xee, 0x1c, 0x3d, 0x7b, 0xcd, 0x6f, 0xf6, 0x5a, 0x9a, 0x5f, 0xfc, 0x66, 0x17, 0xc4, 0x52,
	0x15, 0xfd, 0x07, 0x1e, 0x06, 0xe4, 0x56, 0x9f, 0x4e, 0xa3, 0xcf, 0xdc, 0x6b, 0x4c, 0x5d, 0xea,
	0xdf, 0xd0, 0xf6, 0x86, 0x30, 0x74, 0xd7, 0x11, 0x3a, 0x84, 0xdd, 0x22, 0x3c, 0x24, 0xf3, 0x76,
	0x5d, 0x68, 0xaf, 0xc2, 0xe8, 0x15, 0xa8, 0x01, 0xb9, 0x1d, 0x92, 0x79, 0x40, 0x43, 0xa6, 0x07,
	0xdc, 0x7a, 0xbb, 0x21, 0x54, 0xd7, 0x70, 0xed, 0x7b, 0x05, 0xb6, 0x4b, 0x1e, 0xa2, 0x87, 0xb0,
	0x7b, 0xae, 0x5b, 0x23, 0xcb, 0x7e, 0x3b, 0x31, 0xcc, 0xe1, 0xc0, 0xb1, 0x46, 0xea, 0x03, 0xd4,
	0x81, 0x83, 0x15, 0x70, 0xd2, 0x1d, 0xd8, 0x3d, 0x0b, 0xbf, 0xd7, 0x47, 0xd6, 0xc0, 0x56, 0x15,
	0xf4, 0x02, 0x9e, 0x0d, 0xf1, 0xa0, 0x6b, 0x3a, 0x0e, 0x57, 0x3a, 0xc1, 0xa6, 0xf9, 0x81, 0xab,
	0xd8, 0x66, 0x57, 0x28, 0x54, 0xd0, 0x13, 0xd8, 0x2f, 0x28, 0x9c, 0x5b, 0xa3, 0x53, 0x03, 0xeb,
	0xe7, 0x7a, 0x5f, 0xad, 0x22, 0x80, 0xba, 0xde, 0x1d, 0x59, 0x67, 0xa6, 0x5a, 0xd3, 0x7e, 0xab,
	0x40, 0x43, 0xba, 0x88, 0xfe, 0x0d, 0x35, 0x36, 0x8f, 0xa9, 0xc8, 0xdd, 0xce, 0xd1, 0x93, 0x2c,
	0xae, 0xf2, 0x70, 0xf1, 0x3b, 0x9a, 0xc7, 0x14, 0x0b, 0x35, 0xf4, 0x08, 0xea, 0x24, 0xbb, 0x6d,
	0x96, 0x2f, 0x29, 0xa1, 0x7f, 0xc1, 0x9e, 0x9b, 0x50, 0xc2, 0xfc, 0x28, 0x1c, 0xf9, 0x01, 0x4d,
	0x19, 0x09, 0x62, 0x91, 0xab, 0x2a, 0x5e, 0x3f, 0x40, 0xc7, 0xd0, 0xf2, 0xc3, 0x9b, 0xc8, 0x77,
	0xe9, 0x7b, 0x1a, 0x44, 0x22, 0xc6, 0xad, 0xa3, 0xbd, 0xcc, 0xb6, 0xb5, 0x3c, 0xc0, 0x45, 0x2d,
	0xf4, 0x1c, 0x20, 0xa1, 0x1e, 0xa5, 0xc1, 0xe8, 0xd6, 0x32, 0x44, 0xb0, 0x9b, 0xb8, 0x80, 0xf0,
	0xba, 0x8e, 0x33, 0x7f, 0x4f, 0x49, 0x7a, 0xdd, 0xde, 0x14, 0x0a, 0x45, 0x88, 0x6b, 0x78, 0x34,
	0x65, 0x7e, 0x28, 0xdc, 0x69, 0x37, 0x33, 0x8d, 0x02, 0xa4, 0x9d, 0x40, 0xab, 0x70, 0x67, 0xd4,
	0x82, 0xc6, 0x32, 0x3f, 0x3b, 0x00, 0x85, 0x88, 0x2a, 0x68, 0x13, 0x6a, 0x8e, 0x69, 0x8f, 0xd4,
	0x0a, 0xda, 0x82, 0x4d, 0x6c, 0x76, 0x4d, 0xeb, 0xcc, 0x34, 0xd4, 0xaa, 0xa6, 0xc3, 0x96, 0xe4,
	0x48, 0xfb, 0x7e, 0xca, 0xd0, 0x7f, 0x61, 0x2b, 0x2e, 0xc8, 0x6d, 0xa5, 0x53, 0x3d, 0x6c, 0x1d,
	0x6d, 0x97, 0x22, 0x8d, 0x4b, 0x2a, 0xda, 0x1b, 0x38, 0x70, 0x68, 0xe8, 0xd9, 0x79, 0x2f, 0x50,
	0xaf, 0x1b, 0xf9, 0x61, 0x8a, 0xe9, 0xa7, 0x19, 0x4d, 0x19, 0x6f, 0x2f, 0xe2, 0x79, 0x09, 0x4d,
	0x53, 0xd9, 0x73, 0x0b, 0x51, 0x73, 0x60, 0x6f, 0x48, 0xe6, 0x32, 0x86, 0x0b, 0xf5, 0x65, 0xd2,
	0x94, 0x52, 0xd2, 0x5e, 0xc2, 0x8e, 0x34, 0x2b, 0x35, 0x45, 0xb3, 0x36, 0xf1, 0x0a, 0xaa, 0xfd,
	0x58, 0x81, 0x56, 0x21, 0x2d, 0x32, 0x8e, 0x6e, 0xe2, 0xc7, 0x22, 0x8e, 0x4a, 0x1e, 0xc7, 0x05,
	0x54, 0xb0, 0x58, 0x29, 0x59, 0x3c, 0x80, 0x66, 0x4c, 0xe6, 0x94, 0xda, 0x24, 0xc8, 0x3a, 0xbe,
	0x89, 0x97, 0x00, 0x9f, 0x3b, 0x42, 0xb0, 0x02, 0x72, 0x45, 0xc7, 0xb8, 0x2f, 0x0a, 0xa8, 0x89,
	0xcb, 0xe0, 0x82, 0x23, 0x11, 0x1c, 0x1b, 0x4b, 0x8e, 0xa4, 0xc8, 0x91, 0xe4, 0x1c, 0xf5, 0x25,
	0x47, 0x0e, 0xf2, 0x46, 0x67, 0x09, 0x09, 0xd3, 0x4b, 0x9a, 0x2c, 0xae, 0xde, 0x10, 0x33, 0x6e,
	0x15, 0xe6, 0x37, 0xa1, 0xb7, 0xb1, 0x9f, 0xcc, 0x45, 0x41, 0x55, 0xb1, 0x94, 0x34, 0x0f, 0x1a,
	0x32, 0x24, 0xe8, 0x9f, 0x50, 0x0b, 0x78, 0x19, 0x2b, 0xf7, 0x95, 0xb1, 0x38, 0xe6, 0x49, 0x4b,
	0x29, 0x63, 0x53, 0xea, 0xc9, 0x79, 0xba, 0x10, 0x45, 0x3a, 0x03, 0x36, 0x24, 0xbe, 0x27, 0xbb,
	0x6a, 0x21, 0x6a, 0xbf, 0x56, 0x60, 0xcf, 0x8e, 0x98, 0x7f, 0xe9, 0xbb, 0xa2, 0x40, 0xcd, 0x1b,
	0xde, 0xb3, 0xff, 0x2f, 0xf5, 0xec, 0x61, 0x66, 0x70, 0x4d, 0xad, 0x84, 0x14, 0x5a, 0x18, 0x81,
	0x58, 0x0b, 0xed, 0x4a, 0xa7, 0x7a, 0xd8, 0xc4, 0xd9, 0x8a, 0xf8, 0x5d, 0x01, 0x75, 0x55, 0x1d,
	0x35, 0x61, 0x03, 0x9b, 0xba, 0xf1, 0x9d, 0xfa, 0x80, 0x0f, 0x16, 0xcb, 0xb6, 0x46, 0x96, 0xde,
	0xb7, 0x3e, 0x88, 0x69, 0x34, 0xe9, 0xe9, 0x56, 0xdf, 0x34, 0x54, 0x85, 0xcf, 0x32, 0xbd, 0xdb,
	0x1d, 0x8c, 0xed, 0xd1, 0xa4, 0x7b, 0xaa, 0xdb, 0x6f, 0x4d, 0x43, 0xad, 0x20, 0x15, 0xb6, 0x2c,
	0xfb, 0x6c, 0x60, 0x75, 0xcd, 0xc9, 0x50, 0xb7, 0x0c, 0xb5, 0x8a, 0xfe, 0x0e, 0x2f, 0xf0, 0x60,
	0x2c, 0xa6, 0x9b, 0x3d, 0x30, 0xcc, 0xc2, 0xdc, 0xca, 0x3f, 0xab, 0xa1, 0xa7, 0xf0, 0xa8, 0x6f,
	0xbd, 0x3d, 0x1d, 0xd9, 0x5c, 0xcd, 0x31, 0xf1, 0x19, 0x27, 0x30, 0x06, 0xe7, 0xb6, 0xba, 0xc1,
	0xc7, 0x63, 0x6f, 0x6c, 0x1b, 0x13, 0xdd, 0x30, 0xb0, 0xe9, 0x38, 0x93, 0xb1, 0xed, 0x0c, 0xcd,
	0x82, 0xd1, 0x3a, 0xff, 0xfa, 0x44, 0xef, 0xbe, 0x1b, 0x0f, 0x27, 0x3d, 0xab, 0x6f, 0x3a, 0x13,
	0xfd, 0x4c, 0xb7, 0xfa, 0xfa, 0x49, 0xdf, 0x54, 0x1b, 0xda, 0x4f, 0x0a, 0xa8, 0xba, 0xe7, 0xf5,
	0x66, 0xa1, 0x67, 0x85, 0x3e, 0xc3, 0x34, 0x9e, 0xce, 0xef, 0x6f, 0x23, 0x3e, 0xce, 0x96, 0x13,
	0x5f, 0xf6, 0xa0, 0x2c, 0xe5, 0xf5, 0x03, 0xa4, 0xc1, 0x16, 0x4d, 0x92, 0x28, 0x79, 0x9f, 0x6d,
	0x5f, 0x59, 0xd8, 0x25, 0x8c, 0x4f, 0xaf, 0x0b, 0xe2, 0x7e, 0x9c, 0xc5, 0xdf, 0xa4, 0x51, 0x28,
	0x0b, 0xbb, 0x80, 0x68, 0x47, 0xb0, 0x25, 0xfd, 0xcb, 0x7c, 0x5b, 0xe5, 0x54, 0xd6, 0x39, 0xb5,
	0x01, 0x6c, 0x63, 0x7a, 0x29, 0x3e, 0xf9, 0x93, 0xb9, 0xc0, 0xdb, 0x22, 0x11, 0xaa, 0xba, 0x3c,
	0xcf, 0x3a, 0xbd, 0x0c, 0x6a, 0x3f, 0x28, 0xb0, 0xcb, 0x5d, 0x90, 0x8b, 0x54, 0x38, 0xf2, 0x26,
	0x5f, 0xbd, 0x59, 0xb9, 0x75, 0xb2, 0x72, 0x5b, 0x51, 0x2b, 0xca, 0x52, 0x5f, 0x3b, 0x01, 0x58,
	0xa2, 0x7c, 0x96, 0xda, 0x83, 0x09, 0x4f, 0xa1, 0xfa, 0x00, 0xb5, 0xe1, 0x6f, 0x8b, 0x5d, 0xb7,
	0xb2, 0xe3, 0xb6, 0xa1, 0x29, 0x11, 0x5e, 0x48, 0x9a, 0x09, 0x7b, 0x98, 0x06, 0xd1, 0x0d, 0xed,
	0x7d, 0xd5, 0x35, 0xef, 0x99, 0x3b, 0x9a, 0x05, 0xbb, 0x45, 0x1a, 0x7e, 0x2f, 0x04, 0x35, 0x76,
	0x9b, 0x3f, 0x5a, 0xc4, 0xdf, 0x6b, 0x41, 0xaf, 0xdc, 0x11, 0xf4, 0x5f, 0x2a, 0xb0, 0xeb, 0x7c,
	0x26, 0xb1, 0x8c, 0x99, 0x15, 0x5e, 0x46, 0x5f, 0x70, 0xa8, 0x93, 0x2f, 0x14, 0xb1, 0x94, 0x32,
	0xc2, 0x22, 0xc4, 0x47, 0x51, 0x37, 0x0a, 0x2f, 0xfd, 0x24, 0xa0, 0x9e, 0x5e, 0x5c, 0xad, 0xab,
	0x30, 0x7a, 0x03, 0x8f, 0x73, 0x68, 0xc4, 0xc7, 0x14, 0x71, 0x79, 0xaf, 0x5a, 0x1e, 0x7f, 0x15,
	0xf1, 0x5e, 0xbe, 0xef, 0x98, 0x17, 0x1f, 0x1f, 0x27, 0x92, 0x3e, 0x7b, 0x00, 0x15, 0x10, 0x7e,
	0x5e, 0x78, 0x11, 0xd6, 0xc5, 0x8b, 0xb0, 0x80, 0xac, 0xc5, 0xa5, 0x71, 0x47, 0x81, 0xbf, 0x84,
	0x9d, 0x29, 0x49, 0x59, 0x56, 0x90, 0x62, 0x45, 0x67, 0x1b, 0x78, 0x05, 0xd5, 0x7a, 0xa5, 0xf0,
	0x89, 0x0d, 0x79, 0x0c, 0x4d, 0x19, 0x2f, 0x9a, 0xca, 0xf5, 0xb8, 0x9f, 0x55, 0xd9, 0x4a, 0xa0,
	0xf1, 0x52, 0x8f, 0xd7, 0xea, 0xb3, 0x2e, 0x7f, 0x59, 0x50, 0x4c, 0x98, 0x7b, 0x4d, 0x99, 0x43,
	0xd3, 0xd4, 0x8f, 0xc2, 0xc2, 0xe0, 0x4e, 0xa9, 0x9b, 0x50, 0x26, 0x53, 0x22, 0x25, 0x7e, 0x97,
	0x84, 0x06, 0x11, 0xa3, 0xc3, 0xd9, 0xc5, 0x3b, 0x3a, 0x5f, 0xe4, 0xb8, 0x88, 0xf1, 0x15, 0x93,
	0x66, 0x6c, 0x96, 0xb1, 0x58, 0x53, 0x39, 0x50, 0x58, 0x09, 0xbc, 0x8d, 0x6b, 0xf9, 0x4a, 0xf0,
	0xe1, 0xc9, 0xdd, 0x0e, 0xf1, 0x72, 0x2b, 0x51, 0x2a, 0x77, 0x50, 0x4a, 0x67, 0x2b, 0x25, 0x67,
	0x1f, 0x41, 0x3d, 0xce, 0xdc, 0xcc, 0xbc, 0x90, 0x92, 0xf6, 0x09, 0x1e, 0x97, 0x8d, 0x88, 0xe8,
	0x7c, 0x85, 0xa1, 0x03, 0x68, 0xfa, 0xa1, 0xcf, 0x7c, 0xc2, 0xf2, 0x35, 0xb4, 0x04, 0xd0, 0x53,
	0xd8, 0x9c, 0xa5, 0x34, 0xe1, 0x64, 0xd2, 0x60, 0x2e, 0x6b, 0xdf, 0xc2, 0x41, 0xd9, 0xa4, 0x43,
	0x59, 0x66, 0x35, 0x8b, 0xf7, 0x97, 0xed, 0x16, 0x99, 0x2b, 0x2b, 0xcc, 0x03, 0xd8, 0x97, 0xcc,
	0x66, 0xe8, 0x26, 0xf3, 0x98, 0x7d, 0x1d, 0x65, 0x1b, 0x1a, 0x41, 0xa9, 0x4f, 0x17, 0xa2, 0x46,
	0x72, 0x42, 0x83, 0xfe, 0x05, 0xc2, 0x57, 0xa0, 0xd2, 0xcc, 0x01, 0xea, 0x95, 0x27, 0xc0, 0x1a,
	0xae, 0x8d, 0x61, 0xff, 0x24, 0x8a, 0x58, 0xca, 0x12, 0x12, 0xf7, 0xfc, 0x29, 0xcd, 0x9f, 0x66,
	0xcf, 0x01, 0xce, 0xa3, 0xe4, 0xa3, 0x1f, 0x5e, 0x19, 0x7e, 0x22, 0x6d, 0x14, 0x10, 0xee, 0x42,
	0x6f, 0x36, 0x9d, 0x0e, 0x09, 0xbb, 0x4e, 0xe5, 0x0a, 0x5e, 0x02, 0x17, 0x75, 0xf1, 0x7f, 0xdb,
	0xf1, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x26, 0x7e, 0xe7, 0xc9, 0x0d, 0x00, 0x00,
}
